cmd/create.go
pkg/configs/configs.go
pkg/deployments/deployments.go
pkg/languages/languages.go
pkg/osutil/osutil.go

fixing argument reading

---

Makefile
cmd/create.go
cmd/root.go
go.mod
pkg/configs/createConfig.go

adding ability to use a config for create (helps automate testing)

making config based

---

README.md

add integration test gen info to README

integration test gen readme

---

README.md

Fixed 'LICENSE' spelling.

---

.github/workflows/releases.yml

removed releasing to aks app in draft release

Fixed release pipeline

---

pkg/providers/azure.go
pkg/providers/providersutils.go

handling some errors and adding some logs for better debugging

adding better error logging and handling in providers

---

cmd/create.go

added a flag `--skip-file-detection` in `create` to skip prompting

added skip file detection flag

---

Makefile

adding .exe to the end of the windows binary to fix windows strangeness

adding .exe to the end of windows binary

---

pkg/providers/azure.go

Fixes https://github.com/Azure/draft/issues/102
Handles the logging of command output via log.Printf("%s\n", out) vs log.Fatal. Returns errors that can be handled.
Signed-off-by: Aaron Wislang <aaron.wislang@microsoft.com>

[draft setup-gh] Avoid log.Fatal, return errors.

---

cmd/create.go
cmd/create_test.go
pkg/deployments/deployments.go
pkg/languages/languages.go
pkg/languages/languages_test.go
pkg/osutil/osutil.go
pkg/osutil/osutil_test.go
pkg/templatewriter/templatewriter.go
pkg/templatewriter/writers/filemapwriter.go
pkg/templatewriter/writers/filemapwriter_test.go
pkg/templatewriter/writers/localfswriter.go

Adding ability to get map[string][]byte from languages to have generated Dockerfile bytes directly

Adding copy to FileMap functionality to languages

---

.github/pull_request_template.md

Add Pull request template for folks as a recommendation. cc: ☕️💡 @imiller31 , @qpetraroia , @gambtho and @bfoley13

Add Pull request Template.

---

template/deployments/helm/charts/templates/deployment.yaml
template/deployments/helm/charts/values.yaml
template/deployments/helm/draft.yaml
template/deployments/kustomize/base/deployment.yaml
template/deployments/kustomize/draft.yaml
template/deployments/kustomize/overlays/production/deployment.yaml
template/deployments/manifests/draft.yaml
template/deployments/manifests/manifests/deployment.yaml

Add custom ImageName templating to the deployment templates, with a fallback/default to APPNAME if not supplied
The `latest` tag is implicit, so it was removed from the helm deployment template

add imagename variable for deployments

---

.github/workflows/integration-install.yml
scripts/install.sh

The current script does not install draft and returns a 404
This PR corrects the path to the raw script from this repo
Also added an integration test to validate the functionality of the install script added in #147

add integration test for the install script

---

README.md

Thank you all for taking time for this PR.
This is Documentation update for the `installation` script. This update should help in broadcasting information which is needed to close #143 

Update Installation instructions.

---

CHANGELOG.md

releasing updated info and dryrun

v0.0.27 release changelog

---

pkg/workflows/workflows.go
starterWorkflows/azure-kubernetes-service-helm.yml
starterWorkflows/azure-kubernetes-service-kompose.yml
starterWorkflows/azure-kubernetes-service-kustomize.yml
starterWorkflows/azure-kubernetes-service.yml

Duplicate of #171 with one signed commit

Updated set context and added kubelogin

---

template/deployments/helm/charts/templates/deployment.yaml

Enforce helm namespace in deployment yaml

helm namespace bugfix

---

CHANGELOG.md

helm namespace bugfix release

---

CHANGELOG.md

Release v0.0.31

---

.github/workflows/integration-linux.yml
cmd/update.go
test/gen_integration.sh
test/update_dry_run_schema.json

Implemented dry-run flag for update command

Dry-run for update command

---

pkg/embedutils/embedutil.go
pkg/workflows/workflows.go
pkg/workflows/workflows_test.go
test/gen_integration.sh
test/templates/invalid_deployment.yaml
test/templates/unsupported_no_of_containers.yaml

Merged PR between 
https://github.com/Azure/draft/pull/200
and
https://github.com/Azure/draft/pull/203
Path duplication issue when generating workflows (i.e .github/workflows/.github/workflows being where workflows are placed)
Fixes the bug and adds more unit tests

Bug Fix: destination path duplication fix

---

CHANGELOG.md

- [#197](https://github.com/Azure/draft/pull/197) Add dry run support to `update` command
- [#191](https://github.com/Azure/draft/pull/191) Add variable flag to `create` command
- [#196](https://github.com/Azure/draft/pull/196) Update deprecated node12 actions
- [#194](https://github.com/Azure/draft/pull/194) Move generate workflow templates to embedded file system

Release v0.0.32

---

CHANGELOG.md

Hotfix to update v0.0.32 release with fixed default deploy type
https://github.com/Azure/draft/pull/207

fix release- default deploy type fix

---

.github/workflows/release-and-publish.yml
CHANGELOG.md

Our release actions in the changelog workflow need to be updated
Also the formatting of the changelog was fixed, which will trigger a re-rerelease to patch the previous one
Existing test suites

bump release actions and re-release

---

pkg/providers/providersutils.go

update our error link for installing the ghcli
Update error link

update ghcli link

---

pkg/safeguards/lib/v1.0.0/container-restricted-image-pulls/constraint.yaml
pkg/safeguards/lib/v1.0.0/container-restricted-image-pulls/template.yaml
pkg/safeguards/lib/v1.0.0/disallowed-bad-pod-disruption-budgets/constraint.yaml
pkg/safeguards/lib/v1.0.0/disallowed-bad-pod-disruption-budgets/template.yaml
pkg/safeguards/lib/v1.0.0/parameters/BUILD.bazel
pkg/safeguards/lib/v1.0.0/parameters/map.go
pkg/safeguards/lib/v1.0.0/pod-enforce-antiaffinity/constraint.yaml
pkg/safeguards/lib/v1.0.0/pod-enforce-antiaffinity/template.yaml
pkg/safeguards/lib/v1.0.0/restricted-labels/constraint.yaml
pkg/safeguards/lib/v1.0.0/restricted-labels/template.yaml
pkg/safeguards/lib/v1.0.0/restricted-node-edits/constraint.yaml
pkg/safeguards/lib/v1.0.0/restricted-node-edits/template.yaml
pkg/safeguards/lib/v1.0.0/restricted-taints/constraint.yaml
pkg/safeguards/lib/v1.0.0/restricted-taints/template.yaml
pkg/safeguards/lib/v1.0.0/unique-service-selectors/constraint.yaml
pkg/safeguards/lib/v1.0.0/unique-service-selectors/template.yaml

Adding new safeguards to Draft repo

[ignore]Addding new Safeguards

---

cmd/validate.go
cmd/validate_test.go
pkg/safeguards/safeguards.go
pkg/safeguards/safeguards_helpers.go
pkg/safeguards/safeguards_test_helpers.go
pkg/safeguards/tests/all/error/all-error-manifest-copy.yaml
pkg/safeguards/tests/all/error/all-error-manifest.yaml
pkg/safeguards/tests/all/success/all-success-manifest-copy.yaml
pkg/safeguards/tests/all/success/all-success-manifest.yaml
pkg/safeguards/tests/container-allowed-images/CAI-error-manifest.yaml
pkg/safeguards/tests/container-allowed-images/CAI-success-manifest.yaml

- TestRunValidate
- Constraint Unit tests

Bugfixing error manifests passing without violations / rehaul of ReadManifests to not use fs.FS object

---

Dockerfile
cmd/validate.go
cmd/validate_test.go
pkg/safeguards/safeguards.go
pkg/safeguards/safeguards_helpers.go
pkg/safeguards/safeguards_test.go
pkg/safeguards/safeguards_test_helpers.go
pkg/safeguards/tests/all/success/all-success-manifest-1.yaml
pkg/safeguards/tests/all/success/all-success-manifest-2.yaml
pkg/safeguards/tests/container-enforce-probes/CEP-success-manifest.yaml
pkg/safeguards/tests/container-limits/CL-success-manifest.yaml
pkg/workflows/charts/production.yaml

remove logging from the safeguards package

refactor out logging from validate package

---

pkg/providers/azure.go

Addressing a comment which was missed in the previous PR
https://github.com/Azure/draft/pull/258

Updated the function to retrive the tenantId

---

pkg/languages/defaults/python_test.go
pkg/reporeader/reporeader.go
pkg/workflows/charts/production.yaml

fixes a flaky unit test that relied on map ordering.

fix flaky map ordering unit test

---

.github/workflows/e2e-info.yml
.github/workflows/integration-json.yml
.github/workflows/integration-linux.yml
.github/workflows/integration-windows.yml
.github/workflows/release-and-publish.yml
.github/workflows/unit-tests.yml
template/dockerfiles/go/Dockerfile
template/dockerfiles/gomodule/Dockerfile
test/gen_integration.sh
test/integration/go/helm.yaml
test/integration/go/kustomize.yaml
test/integration/go/manifest.yaml
test/integration/rust/helm.yaml
test/integration/rust/kustomize.yaml
test/integration/rust/manifest.yaml
test/integration_config.json

bump golang version for new dependencies

Go version bump

---

NOTICE.md

Add component governance NOTICE file

add NOTICE file

---

NOTICE.md

Updating NOTICE file to be compliant with security standards.

Updating NOTICE file

---

CHANGELOG.md

Release including new `draft validate` command from staging

release 0.0.35 including draft validate

---

.github/dependabot.yml

Configurate dependabot to make PRs for updating our actions in generated workflows using the directory option

add dependabot for actions and go

---

.github/workflows/integration-linux.yml
template/workflows/helm/.github/workflows/azure-kubernetes-service-helm.yml
template/workflows/helm/draft.yaml
template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml
template/workflows/kustomize/draft.yaml
template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml
template/workflows/manifests/draft.yaml
test/gen_integration.sh

This PR changes the way we find out if a user's cluster is private from prompting the user to now running an action on the template that returns that information.

Template Support for Private Clusters

---

CHANGELOG.md

release changelog for v0.0.36 including private cluster support updates

Release v0.0.36

---

pkg/config/draftconfig.go
pkg/osutil/osutil.go
template/dockerfiles/erlang/draft.yaml
template/dockerfiles/go/draft.yaml
template/dockerfiles/gomodule/draft.yaml
template/dockerfiles/gradle/draft.yaml
template/dockerfiles/gradlew/draft.yaml
template/dockerfiles/java/draft.yaml
template/dockerfiles/javascript/draft.yaml
template/dockerfiles/php/draft.yaml
template/dockerfiles/python/draft.yaml
template/dockerfiles/ruby/draft.yaml
template/dockerfiles/rust/draft.yaml
template/dockerfiles/swift/draft.yaml

we no longer use name overrides, so this PR removes them

remove name overrides

---

.github/workflows/integration-json.yml
.github/workflows/integration-linux.yml
.github/workflows/integration-windows.yml
test/gen_integration.sh

Exclude .git directories in artifact upload

Add exclusion for .git in artifact upload

---

pkg/config/draftconfig.go
pkg/languages/languages.go
template/dockerfiles/clojure/Dockerfile
template/dockerfiles/csharp/Dockerfile
template/dockerfiles/erlang/Dockerfile
template/dockerfiles/go/Dockerfile
template/dockerfiles/gomodule/Dockerfile
template/dockerfiles/gradle/Dockerfile
template/dockerfiles/gradlew/Dockerfile
template/dockerfiles/java/Dockerfile
template/dockerfiles/javascript/Dockerfile
template/dockerfiles/php/Dockerfile
template/dockerfiles/python/Dockerfile
template/dockerfiles/ruby/Dockerfile
template/dockerfiles/rust/Dockerfile
template/dockerfiles/swift/Dockerfile

Migrating dockerfiles to Gotemplates

---

pkg/deployments/deployments_test.go
pkg/fixtures/deployments/charts/.helmignore
pkg/fixtures/deployments/charts/Chart.yaml
pkg/fixtures/deployments/charts/production.yaml
pkg/fixtures/deployments/charts/templates/_helpers.tpl
pkg/fixtures/deployments/charts/templates/deployment.yaml
pkg/fixtures/deployments/charts/templates/service.yaml
pkg/fixtures/deployments/charts/values.yaml
pkg/fixtures/validatetemplate.go
template/dockerfiles/erlang/draft.yaml
test/info_schema.json
test/integration/erlang/helm.yaml
test/integration/erlang/kustomize.yaml
test/integration/erlang/manifest.yaml
test/integration_config.json

added fixtures to deployment unit tests

added fixtures to deployment unit tests

---

pkg/fixtures/workflows/azure-kubernetes-service-helm.yml
pkg/fixtures/workflows/azure-kubernetes-service-kustomize.yml
pkg/fixtures/workflows/azure-kubernetes-service.yml
pkg/workflows/workflows_test.go

Adding fixtures to the workflow unit tests

adding fixtures to the workflow unit tests

---

pkg/config/draftconfig_template_test.go
template/manifests/PodDisruptionBudget/manifest/draft.yaml
template/manifests/PodDisruptionBudget/manifest/pdb.yaml

creating PDB template

---

pkg/handlers/template.go
pkg/handlers/template_test.go

Need to normalize the filename output of the template generation for existing usage

Normalize filename output

---

CHANGELOG.md

Release for the filename normalization bugfix

New release for filename output normalizing

---

CHANGELOG.md

- [#388](https://github.com/Azure/draft/pull/388) Migrate createRole assignment to Az SDK
- [#405](https://github.com/Azure/draft/pull/405) adding generic service templates
- [#412](https://github.com/Azure/draft/pull/412) Migrate workflows to template handler
- [#409](https://github.com/Azure/draft/pull/409) Add Trandformer and Validators to template handling
- [#419](https://github.com/Azure/draft/pull/419) Add configmap handling to deployment templates
- [#418](https://github.com/Azure/draft/pull/418) Ensure GH and AZ cli changes
- [#392](https://github.com/Azure/draft/pull/392) Validate helm and kustomize support
- [#428](https://github.com/Azure/draft/pull/428) Update template versioning definition
- [#430](https://github.com/Azure/draft/pull/430) Update templates and testing and …

New Draft Release

---

CHANGELOG.md

Change Log
[#437](https://github.com/Azure/draft/pull/437) Bumps the actions group with 10 updates in the /.github/workflows directory
Updating the version as the previous version was already released. 
Please refer the link for all the released versions https://pkg.go.dev/github.com/azure/draft?tab=versions

New Draft Release v0.17.0 to avoid go sumdb collisions

---

CHANGELOG.md

New release adds the following PRs
- [483](https://github.com/Azure/draft/pull/483) Allow user to select language via prompt if none detected
- [486](https://github.com/Azure/draft/pull/486) Uses the default k8s probe values instead of overriding them on tests
- [495](https://github.com/Azure/draft/pull/495) Adds private cluster support for namespace creation/validation in workflow templates
- [497](https://github.com/Azure/draft/pull/497) Reduce base resource requests to 0.5Gi and 0.5 cpu

Release v0.17.4

---

pkg/config/draftconfig_template_test.go
pkg/fixtures/manifests/ingress/ingress-simple.yaml
pkg/fixtures/manifests/ingress/ingress.yaml
pkg/handlers/templatetests/manifests_ingress_test.go
template/manifests/Ingress/manifests/draft.yaml
template/manifests/Ingress/manifests/ingress.yaml
test/integration/rust/helm.yaml
test/integration/rust/kustomize.yaml
test/integration/rust/manifest.yaml

This adds a base ingress template with app-routing support

Adding Ingress Manifest Template

---

CHANGELOG.md

Cut a new release with template updates

Release 0.17.5

---

pkg/fixtures/deployments/helm/charts/production.yaml
template/deployments/helm/charts/production.yaml

Use correct variables in production.yaml for helm deployments

Use correct variables in prod.yaml

---

CHANGELOG.md

prepare release for v0.17.8 with fixed ingress keyvault name to use ingressname draft variable

release v0.17.8

---

CHANGELOG.md

new release with #544 to fix fleet annotation

release v0.17.9 with fleet annotation update

---

CHANGELOG.md

new release 
adds PR #547 to fix deployment templates to have `azure.workload.identity/use` label in pod level spec

Release v0.17.10

---

CHANGELOG.md

Includes PR https://github.com/Azure/draft/pull/558 :  Add new parameter `DOCKERFILE`and env var `dockerfile` to pass the dockerfile path in the az pipeline template

Release v0.17.11

---

CHANGELOG.md

release v0.17.12

---

CHANGELOG.md

Update changelog for releasing v0.17.13
Adds:
- [587: Make replica count configurable across all deployment templates ](https://github.com/Azure/draft/pull/587)
- Dependabot updates for dependencies and actions

Release v0.17.13
