Azure/draft

docs/install.md
For those using the Azure Container Registry ;)
=> docs(install): adding Azure to token generation docs

README.md
=> add link to slack channel

cmd/draft/create.go
=> fix unused --app flag on draft create

cmd/draft/init.go, pkg/draft/pack/create.go, pkg/draft/pack/create_test.go
=> inform user when pack already exists

docs/contributing/hacking.md, docs/ingress.md, docs/install.md
This PR intents to document the steps needed to work with Draft using Minikube.
=> Added documentation on the steps needed to use minikube

pkg/draft/pack/generated/files.go
some code is now autogenerated. Any changes made to draft's default
packs will require a call to `make build`.
=> call make build

docs/install.md
I tried draft [Getting Started](https://github.com/Azure/draft/blob/master/docs/getting-started.md) and failed with the some errors.
I used Azure Container Registry, Azure Container Service, Azure DNS.
I thought it would be better to add a description of the registry.url, basedomain field.
=> Add description of some field

packs/golang/chart/values.yaml, packs/java/chart/values.yaml, packs/node/chart/values.yaml, packs/php/chart/values.yaml, packs/python/chart/values.yaml, packs/ruby/chart/values.yaml
=> revert commit 0b44f84

api/server.go
=> ensure pull secret does get updated

chart/templates/deployment.yaml, cmd/draft/installer/install.go
=> fix(chart): use linux node selector on draftd deployment

Jenkinsfile
This is actually causing the `release-vx.y.z` branch to publish false release candidate builds when instead we want to publish from the tags.
See https://ci.deis.io/job/Azure/job/draft/job/release-v0.4.0/1/
See #138
=> remove "isTag" logic from Jenkinsfile

.gitignore, Jenkinsfile, Makefile, scripts/cover.sh
=> add codecov

.gitignore
New projects created with `draft create` also include this file thanks to #147.
=> add .draftignore to .gitignore

docs/design.md
=> taking charts to prod, add project scope

chart/templates/deployment.yaml, cmd/draft/installer/install.go, cmd/draftd/start.go
Initial implementation of dind sidecar.
=> Issue #150 Use docker-in-docker instead of mounting host docker

docs/design.md
An actual diagram won't be released until we have finalized on the architectural decisions. Right now it's all in the air at this point.
closes #109
=> add architecture description

cmd/draft/init.go
--yes is not descriptive enough of the intent behind the feature flag.
closes #174
=> rename --yes to --auto-accept

CHANGELOG.md
(cherry picked from commit af354f4a811ba12664e34f0c7753a6b66269ae58)
=> add v0.5.1 CHANGELOG

cmd/draft/up.go, cmd/draft/up_test.go
=> fix draft up with set values in environment

cmd/draft/plugin.go, cmd/draft/plugin_install_test.go, cmd/draft/plugin_list_test.go, cmd/draft/plugin_remove.go, cmd/draft/plugin_remove_test.go
=> feat(cmd/draft): add plugin remove cmd

api/server.go, docs/design.md
=> add ondraft value to chart

pkg/draft/context.go, pkg/draft/context_test.go
=> fix app context vals not being properly loaded

docs/ingress.md, docs/install.md
Many users (including myself) were having trouble getting dnsmasq running on MacOS following many different sources of information. I eventually got it running, so I figured I should document it for others' benefit.
closes #199
=> add documentation on setting up dnsmasq for Draft

docs/design.md
Draft recently switched over from HTTP/Websockets to gRPC.
=> fix some verbiage in draft design

pkg/cmdline/cmdline.go
=> ref(draft): add success and fail text on draft up

cmd/draft/installer/install.go
unpacks the grpc error description now
=> ref(cmd/draft): make draft install errors pretty

pkg/draft/context.go, pkg/draft/context_test.go
We're not using this any where right now so removing to prevent confusion!
=> ref(pkg/draft): remove ondraft val

docs/getting-started.md, docs/ingress.md, docs/install.md
=> document `draft connect`

.circleci/deploy-azure.sh
=> install pip

cmd/draft/connect.go, cmd/draft/draft.go, cmd/draft/installer/install.go, cmd/draft/logs.go, pkg/draft/local/local.go, pkg/draft/local/local_test.go
Helps debug draft up failures by tailing draftd pod logs. Resolves #273
=> feat(*): add draft logs command

CHANGELOG.md
(cherry picked from commit 3923967250840bccc952f08fa59574ee7d2923c2)
=> add v0.8.0 CHANGELOG

examples/dotnet/Program.cs, examples/dotnet/README.txt, examples/dotnet/Startup.cs, examples/dotnet/WebApplication.csproj, packs/csharp/Dockerfile, packs/csharp/charts/values.yaml
No replacement for ASP.NET 1.0, but we can eventually come back to that road. For now we should support the latest version of ASP.NET available.
closes #325.
=> bump ASP.NET to 2.0

.circleci/deploy-azure.sh, .circleci/deploy-dockerhub.sh
e.g. https://circleci.com/gh/Azure/draft/233
=> exit non-zero when building branches

.circleci/config.yml, cmd/draft/create_test.go, cmd/draft/ensure.go, cmd/draft/ensure_test.go, cmd/draft/init.go, cmd/draft/init_test.go, cmd/draft/plugin.go, cmd/draft/plugin_list_test.go, cmd/draft/plugin_test.go, cmd/draft/testdata/plugins/echo/plugin.yaml, pkg/draft/pack/load_test.go, pkg/plugin/builtins.go, pkg/plugin/installer/base.go, pkg/plugin/installer/local_installer.go
=> feat(cmd/draft): clarify plugin setup in init

cmd/draft/create.go, cmd/draft/create_test.go
Fixes #209! 
:wave: Hi @bacongobbler! I thought this would be a quick and easy fix to solve issue #209. Let me know what you think!
=> Adding prerun hook to lowercase application names

Gopkg.lock
the latest version of `dep` prettifies the lockfile as nicely-formatted TOML.
=> prettify lockfile

charts/draftd/templates/deployment.yaml, cmd/draft/installer/templates.go
This reverts commit 0f699021b60031e41d08cdff69ff1699f6db4cd0.
closes #443
=> Revert "remove docker-in-docker container"

cmd/draft/create.go, cmd/draft/create_test.go, cmd/draft/testdata/create/generated/html-but-actually-go/.draftignore, cmd/draft/testdata/create/generated/html-but-actually-go/Dockerfile, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/.helmignore, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/Chart.yaml, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/templates/NOTES.txt, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/templates/_helpers.tpl, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/templates/deployment.yaml, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/templates/ingress.yaml, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/templates/service.yaml, cmd/draft/testdata/create/generated/html-but-actually-go/charts/go/values.yaml, cmd/draft/testdata/create/generated/html-but-actually-go/draft.toml, cmd/draft/testdata/create/generated/html-but-actually-go/loremipsum.html, cmd/draft/testdata/create/generated/html-but-actually-go/main.go, cmd/draft/testdata/create/src/html-but-actually-go/loremipsum.html, cmd/draft/testdata/create/src/html-but-actually-go/main.go, pkg/draft/pack/errors.go
=> select the most popular language found with a pack

pkg/storage/storage.go
as seen in https://circleci.com/gh/Azure/draft/392
=> fix linting errors

CHANGELOG.md
(cherry picked from commit f2b9c89dad0b6e8e16114309a96e67eda3fd0349)
=> add v0.10.0 CHANGELOG

cmd/draftd/draftd.go, cmd/draftd/start.go
=> fix(512): pull draftd namespace from env

pkg/rpc/client.go
=> Fix context passed to GetLogs

pkg/cmdline/cmdline.go
=> add informational message to inspect the logs

cmd/draft/logs.go
this allows us to test for the command's output
=> print output to l.out

pkg/build/build_test.go, pkg/build/testdata/simple/Dockerfile
the test is dumb, but it's more than no coverage!
=> add test for archiveSrc()

CHANGELOG.md
(cherry picked from commit 5c9c07809e5f67e8a2711fff5fa5c89ba4bd2d9f)
=> add v0.11.0 CHANGELOG

cmd/draft/connect.go
=> Add connection message every 5 minutes

docs/reference/dep-003.md
=> document more on the Naive Bayesian Classifier

NOTICE, README.md, cmd/draft/testdata/drafthome/packs/github.com/Azure/draft/packs/go/NOTICE, packs/csharp/NOTICE, packs/go/NOTICE, packs/gradle/NOTICE, packs/java/NOTICE, packs/javascript/NOTICE, packs/php/NOTICE, packs/python/NOTICE, packs/ruby/NOTICE
We've no longer relied on Heroku buildpacks for quite some time.
=> remove Heroku notices

pkg/draft/pack/repo/repo.go
=> Fix FindRepositories path issue on Windows

CHANGELOG.md
(cherry picked from commit 53924464463d2474f410415f1310d2b95fb8965f)
=> add v0.12.0 CHANGELOG

README.md, docs/install-advanced.md, docs/install.md
This is a first pass at updating the docs to alert users what's going on with this release relative to others. It is NOT the correct fix, as we need to explain how the system works better at the conceptual level. But, baby steps, baby steps.
=> updating documentation to highlight the major changes in 0.12

cmd/draft/config.go
=> truncate config file on save

README.md, docs/install-cloud.md, docs/install-minikube.md
=> Dot 13: updated documentation 

README.md
folks should be able to see what draft does
as quickly as possible
=> ref(README): move description up

cmd/draft/create.go, pkg/draft/pack/create.go, pkg/draft/pack/repo/repo.go, pkg/draft/pack/repo/repo_test.go, pkg/draft/pack/repo/testdata/packs/github.com/testOrg1/testRepo1/packs/testpack1/something.txt, pkg/draft/pack/repo/testdata/packs/github.com/testOrg1/testRepo1/packs/testpack2/charts/testpack2/Chart.yaml, pkg/draft/pack/repo/testdata/packs/github.com/testOrg1/testRepo1/packs/testpack2/something.txt
resolves #653 without handling multiple packs scenario. will handle pack collisions (#509) in next commit or PR
=> fix(cmd/draft): fix --pack flag

docs/getting-started.md
=> fix broken link

cmd/draft/delete.go, cmd/draft/delete_test.go
=> Avoid deleting any Helm app and add environment flag for delete

cmd/draft/create.go, pkg/osutil/osutil_test.go
=> fixup calls to path.Join with filepath.Join

packs/clojure/charts/values.yaml, packs/csharp/charts/values.yaml, packs/go/charts/values.yaml, packs/gradle/charts/values.yaml, packs/java/charts/values.yaml, packs/javascript/charts/values.yaml, packs/php/charts/values.yaml, packs/python/charts/values.yaml, packs/ruby/charts/values.yaml, packs/rust/charts/values.yaml, packs/swift/charts/values.yaml
bc we probably don't need 2 in dev as a default
=> ref(packs): change default replicaCount to 1

docs/install-cloud.md
=> docs(install): add short section on using DockerHub

Gopkg.lock, cmd/draft/ensure.go, cmd/draft/ensure_test.go, cmd/draft/plugin.go, cmd/draft/plugin_install.go, cmd/draft/plugin_remove.go, cmd/draft/plugin_unix.go, cmd/draft/plugin_update.go, cmd/draft/plugin_windows.go, cmd/draft/testdata/plugins/echo/plugin.yaml, pkg/plugin/hooks.go, pkg/plugin/plugin.go, pkg/plugin/plugin_test.go, pkg/plugin/testdata/plugdir/downloader/plugin.yaml, pkg/plugin/testdata/plugdir/echo/plugin.yaml, pkg/plugin/testdata/plugdir/hello/plugin.yaml
addresses #396, but doesn't close it until draft-pack-repo supports this as well (working on a PR, should be ready by tomorrow)
=> run plugin hooks using powershell in windows

Gopkg.lock, cmd/draft/delete.go, cmd/draft/testdata/create/generated/empty/draft.toml, cmd/draft/testdata/create/generated/html-but-actually-go/draft.toml, cmd/draft/testdata/create/generated/simple-go-with-draftignore/draft.toml, cmd/draft/testdata/create/generated/simple-go/draft.toml, cmd/draft/up.go, docs/reference/dep-003.md, docs/reference/dep-008.md, docs/reference/index.md, pkg/draft/local/local.go, pkg/draft/manifest/manifest.go, pkg/draft/manifest/manifest_test.go, pkg/draft/pack/pack.go, pkg/draft/pack/pack_test.go, pkg/kube/podutil/podutil.go, pkg/tasks/tasks.go, pkg/tasks/tasks_test.go, pkg/tasks/testdata/malformedTasks.toml, pkg/tasks/testdata/tasks.toml
=> feat(*): run pre-up, post-deploy, and cleanup tasks in draft

pkg/plugin/builtins.go
Note that this won't actually work until v0.4.0 is out.
closes #682
=> bump pack-repo to 0.4.0

cmd/draft/up.go
=> fix(cmd/draft/up): fix panic when missing task file

.circleci/bootstrap.sh, .circleci/deploy-azure.sh, Makefile, docs/install-minikube.md
=> add windows canary binary to canary list

CHANGELOG.md
(cherry picked from commit a2d217487caa2ea1186682080f469b6bd0efe197)
=> add v0.14.0 CHANGELOG

pkg/plugin/builtins.go
=> bump pack-repo to v0.4.2

Makefile
=> generate checksums for .zip files

README.md
*places install instructions higher up for quickstart
resolves #734
=> ref(README): make it easier to find install instru

docs/getting-started.md, docs/reference/dep-006.md
wait defaults to true as of #642. This updates docs to reflect that change so that a newcomer is not confused.
=> ref(docs): update wait=true by default

pkg/draft/pack/create_test.go, pkg/draft/pack/load.go, pkg/draft/pack/load_test.go, pkg/draft/pack/pack.go, pkg/draft/pack/testdata/DirWithNestedDirs/dirA/file.txt, pkg/draft/pack/testdata/DirWithNestedDirs/dirB/nestedDir/another-file.txt, pkg/draft/pack/testdata/DirWithNestedDirs/nested-file.md, pkg/draft/pack/testdata/pack-python/scripts/some-script.sh
* draft create currently only copies top level files
* This PR allows draft to copy directories and nested files
over to the current working directory as well
resolves #743
=> ref(*): deep copy from draft pack to current dir

docs/README.md, docs/quickstart.md
taking a stab at re-vamping docs #742
=> feat(docs): add quickstart guide & README

docs/README.md, docs/examples-and-tutorials.md, docs/quickstart.md
=> feat(docs): add examples and tutorials page

packs/java/Dockerfile
Fix to address issue: https://github.com/Azure/draft/issues/748
=> Changed to use JAR file with dependencies

Gopkg.lock, cmd/draft/draft.go
Adds support for additional auth providers
=> add kubernetes client auth plugins

docs/README.md, docs/advanced-setup.md
=> chore(docs): add docs around draft init --config

cmd/draft/create.go, cmd/draft/create_test.go, pkg/draft/pack/create.go, pkg/draft/pack/create_test.go
Closes https://github.com/Azure/draft/issues/498
Sets ChartName and directory to appName when specified.
=> Set ChartName to appName

CHANGELOG.md
(cherry picked from commit bec5e67fe761e195e08b0be033046b27dd7bef9e)
=> add v0.15.0 CHANGELOG

docs/getting-started.md
Updated the getting-started.md guide with output from latest version of draft as well as more detailed notes around gotchas and issues that one might run into.
=> Updated getting started guide

pkg/draft/pack/create_test.go
As requested by @michelleN in https://github.com/Azure/draft/pull/790
=> Add testing for chartname update from #790

packs/clojure/Dockerfile, packs/go/Dockerfile, packs/javascript/Dockerfile, packs/python/Dockerfile, packs/ruby/Dockerfile
=> Use non-onbuild base images in packs

CONTRIBUTING.md, GOVERNANCE.md
=> add CONTRIBUTING.md

cmd/draft/delete.go, cmd/draft/up.go, docs/getting-started.md, docs/reference/dep-008.md, pkg/tasks/tasks.go, pkg/tasks/tasks_test.go
I took a look at #835 because it seemed relatively simple and a fun way to read some code 🙂
As far as I can tell, `$VARIABLES` _are_ evaluated in all kinds of tasks because both pre-up and post-delete tasks [call through `executeTask`, which in turn calls `evaluateArgs`, which does the `$VARIABLES` expansion](https://github.com/Azure/draft/blob/00cf34da7b70ac9733809115a9be5c7dc5d75c5f/pkg/tasks/tasks.go#L81).
However, there are a few edge cases which I attempt to address in this PR:
* `$VARIABLES` are not expanded unless `$` is the first character in the space-separated argument: `task = "echo /home/$USER"` would not be expanded because a space-separated arg doesn't begin with `$`
* `$VARIABLES` are assumed to take up the entire space-separated argument: `task = "curl -u $USER:$PASS"` …
=> Allow $VARIABLES to exist in any task argument

packs/java/Dockerfile
=> Updated maven pack to java 10

CHANGELOG.md
Signed-off-by: Michelle Noorali <michellemolu@gmail.com>
(cherry picked from commit 4bb30224cb7b7475bb5cab317d31fe4af71f8bc5)
=> add v0.16.0 CHANGELOG

cmd/draft/up.go, docs/getting-started.md
Add skip pushing to registry using flag `--skip-image-push` when using draft up:
https://github.com/Azure/draft/issues/768
=> Add skip push flag

scripts/test-examples.sh
This PR adds an script that test-runs all the examples.
Script is running `draft create`, `draft up` and `draft delete` on all the examples.
=> Script for testing all examples

Gopkg.lock, cmd/draft/draft.go, cmd/draft/up.go, pkg/cmdline/cmdline.go, pkg/cmdline/option.go
=> feat(add): disable emoji flag

packs/gradle/Dockerfile, packs/java/Dockerfile
JDK11 was recently released.
Upgrading gradle and java packs.
=> Packs: upgraded to jdk11

Makefile
shamelessly adapted from deislabs/duffle
=> feat(Makefile): add install target

pkg/builder/docker/builder.go, pkg/builder/registry.go, pkg/builder/registry_test.go
Adding authentication to imageBuild when doing `draft up`. Related to this issue https://github.com/Azure/draft/issues/912
=> Adding authentication to ImageBuild

packs/javascript/Dockerfile
Update javascript pack to reflect current LTS version of node
=> Packs: update javascript to node:10
