- pkg/draft/defaultpacks/node.go
Moving from 8-onbuild -> 6-onbuild
Fixes #80
> fix(nodejs): Fixing nodejs dockerfile to point to older version

- Makefile
- glide.lock
- glide.yaml
- pkg/draft/client.go
This PR intends to fix the Windows compilation.
To do so, I updated the docker version to v17.05.0-ce.
We also had to get the proper dependencies for docker which is not using tag commits.
If need be, I could try to fix it without upgrading docker.
Fixes #61
> fix(windows): Updated to docker version v17.05.0-ce with the needed dependencies

- pkg/draft/defaultpacks/golang.go
- pkg/draft/defaultpacks/java.go
- pkg/draft/defaultpacks/node.go
- pkg/draft/defaultpacks/php.go
- pkg/draft/defaultpacks/python.go
- pkg/draft/defaultpacks/ruby.go
basedomain is refered to in all of the ingress templates, but unset
in default values file, which results in regex validation error for
the ingress object
> fix(defaultpacks): set basedomain

- cmd/draft/create.go
The app is randomly generated right now by default by helm.
It stated before that the app name was the dir name by default.
> ref(draft/create): update app flag description

- packs/golang/detect
See https://github.com/heroku/heroku-buildpack-go/issues/115 for more context on why Heroku originally did not do this, but I think the number of users who have ruby apps with .go files in their repo is very small. Worst case scenario these users can just call `draft create --pack ruby` to explicitly override the system.
closes #101.
> blindly check for .go files across the repository

- api/server.go
keeping it consistent where we set the other values we override in the chart.
> move basedomain to rawVals

- tests/e2e.sh
- tests/testdata/good/example-dockerfile-http/draft.toml
Fix and enhance e2e tests to not block on watch feature of `draft up`. They were previously hanging.
Ensure we clean the right helm chart and get some clearer output.
> E2e test fixes

- Makefile
- docs/contributing/release-checklist.md
We replaced drone with https://ci.deis.io when we migrated from the deis org to Azure. More good, larger bus factor (I was the only maintainer).
Additionally, Jenkins does not support building release tags through Jenkins Pipelines, so this needs to be done manually for now.
See https://issues.jenkins-ci.org/browse/JENKINS-34395 for more info.
> update release checklist

- api/server.go
- api/server_notwin.go
- api/server_windows.go
- cmd/draft/create.go
- cmd/draft/draft.go
- pkg/draft/pack/pack.go
Provides fixes for various Windows compatibility issues. Closes #157
> Add Windows support

- packs/java/Dockerfile
The `onbuild` tags [have been deprecated on the official docker images](https://github.com/docker-library/docs/pull/911).
I've also added [the new multi-stage build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) to compile the application during the `docker build`.
> Using multi-stage to compile the application

- packs/java/Dockerfile
- pkg/draft/pack/generated/files.go
When referencing multiple files in a COPY operation, you must end the argument with a directory name. This fixes the java pack by referencing the exact jar we want to fetch out of the source container.
> fixup java pack

- api/server.go
- chart/values.yaml
- cmd/draft/draft.go
- cmd/draft/init.go
- cmd/draft/installer/config/config.go
- cmd/draft/installer/install.go
- docs/contributing/hacking.md
- docs/design.md
- docs/getting-started.md
- docs/ingress.md
- docs/install.md
- docs/packs.md
- docs/plugins.md
- docs/user-guide.md
closes #82
closes #102
closes #122
closes #152 
closes #167
This is a relatively "large" PR, so here's where we are at today:
- Users can no longer update draft configuration through `-f` and `--set`; user will be prompted for this information instead if required
- `--yes` is available if user wants to auto-accept the defaults
- If "minikube" is detected as the current context in ~/.kube/config, then we assume that they have installed the `ingress` and `registry` addons as well as ran `helm init` after the cluster was created. `draft init` detects this and drops some configuration to use these addons natively
TODO:
> draft init rewrite

- cmd/draft/init.go
- pkg/draft/pack/create_test.go
When GOOS=windows, syscall.Stdin is of type syscall.Handler which is
of type uintptr. Casting to an int is considered the "right" way to
fix this.
> cast syscall.Stdin to an int

- cmd/draft/init.go
reader.ReadString() includes the delimiter in the returned text, so we need to strip that out.
> trim whitespace from answer

- chart/values.yaml
- cmd/draft/installer/install.go
On clusters like minikube (the large majority of users), resources are limited.
We should make the default replica count as 1, then under `draft init` if a cloud
provider (*cough* Azure *wheeze*) wants to have more replicas running for
redundancy purposes, they can.
> lower replica count to 1

- chart/templates/deployment.yaml
- cmd/draft/installer/install.go
fixes docker push to minikube local registry
should be applied to `v0.5.0` as well
> add insecure registry to dind

- cmd/draft/init.go
Fix draft init --yes being ignored
The draft init execution must be unattended when --yes is provided and
a cloud provider is found.
> Fix draft init --yes being ignored

- chart/templates/deployment.yaml
- cmd/draft/installer/install.go
this significantly increases performance and fixes the issue where vfs on overlayfs was causing the disk to fill up rapidly on minikube.
closes #181 
closes #182
> select storage driver as overlay

- cmd/draft/draft.go
- cmd/draft/plugins.go
- cmd/draft/plugins_test.go
closes #206 
Manually tested using the example I provided in #206:
```
><> draft hi
What is your name?
Matt
Hi Matt!
```
> attach os.Stdin to plugin's stdin

- cmd/draft/testdata/create/generated/empty/draft.toml
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/draft.toml
- cmd/draft/testdata/create/generated/simple-go/draft.toml
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
> disable watch feature by default

- cmd/draft/draft.go
- cmd/draft/plugin.go
- cmd/draft/plugin_install.go
- cmd/draft/plugin_install_test.go
- cmd/draft/plugin_list.go
- cmd/draft/plugin_list_test.go
- cmd/draft/plugin_test.go
- cmd/draft/testdata/plugins/echo/plugin.yaml
- docs/design.md
- docs/plugins-guide.md
- glide.lock
- glide.yaml
- pkg/draft/draftpath/home.go
- pkg/plugin/installer/base.go
- pkg/plugin/installer/installer.go
- pkg/plugin/installer/local_installer.go
- pkg/plugin/installer/local_installer_test.go
- pkg/plugin/installer/vcs_installer.go
- pkg/plugin/installer/vcs_installer_test.go
- pkg/plugin/testdata/plugdir/echo/plugin.yaml
This implements the plugin install command. The bulk of this
creates a plugin installer specific for the Draft environment and
it creates the plugin install command with the proper setup.
Addresses #185 by creating a framework for a plugin manager.
> feat(*): install remote and local plugins

- README.md
This video is now out of date as it was based on an earlier version of Draft.
> remove video of Draft on ACS

- cmd/draft/testdata/create/generated/empty/Dockerfile
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/Dockerfile
- cmd/draft/testdata/create/generated/simple-go/Dockerfile
- packs/dotnetcore/Dockerfile
- packs/golang/Dockerfile
- packs/gradle/Dockerfile
- packs/maven/Dockerfile
- packs/node/Dockerfile
- packs/php/Dockerfile
- packs/python/Dockerfile
- packs/ruby/Dockerfile
- pkg/draft/pack/generated/files.go
For users migrating over from Deis Workflow (or from an application that follows 12 Factor best practices), it is common for the app to specify the listening port as $PORT. By providing this environment variable by default, applications like deis/example-python-flask can be deployed by Draft by simply calling `draft create && draft up`.
> add PORT to application environments

- pkg/draft/context.go
- pkg/draft/server.go
Most of the codebase is of the form
import (
stdlib
thirdparty
firstparty
)
This makes the import statements overall more readable. This is also
how `go fmt` formats import statements.
> use go fmt best practices for import statements

- pkg/rpc/server.go
The max message size gRPC uses by default is 4MB. This PR bumps it to 20MB using the grpc.MaxMsgSize server option.
Fixes issue #275
> fix(rpc): bump max recv message size.

- cmd/draft/installer/install.go
- docs/contributing/release-checklist.md
This change was present in charts/ but not in the codebase. #247 should solve this in the future, but this resolves an issue where users were not seeing the latest version of their canary images bring run.
> Change imagePullPolicy on `draft init` canary deployments to "Always"

- Jenkinsfile
- Makefile
`make test-cover` takes over 17 minutes on #269. Removing it will help unblock some CI builds.
```
><> time ./scripts/cover.sh
ok  	github.com/Azure/draft/cmd/draft	6.222s	coverage: 37.2% of statements
ok  	github.com/Azure/draft/cmd/draft/installer	1.642s	coverage: 0.0% of statements
?   	github.com/Azure/draft/cmd/draft/installer/config	[no test files]
?   	github.com/Azure/draft/cmd/draftd	[no test files]
?   	github.com/Azure/draft/examples/go	[no test files]
?   	github.com/Azure/draft/pkg/build	[no test files]
?   	github.com/Azure/draft/pkg/cmdline	[no test files]
ok  	github.com/Azure/draft/pkg/draft	1.860s	coverage: 6.4% of statements
ok  	github.com/Azure/draft/pkg/draft/draftpath	1.019s	coverage: 50.0% of statements
ok  	github.com/Azure/draft/pkg/draft/local	1.658s	coverage: …
```
> use test-unit target

- Makefile
When building release candidates, `make build-cross` still calls `make generate` which causes the binaries to be in a dirty state. `make check-then-generate` should be the default.
closes #211
> make `make check-then-generate` the default

- docs/install.md
Currently trying to fix the homebrew repo due to `draft init --client-only` not working due to permissions issues, but the repo is now public.
closes #250
> add homebrew install instructions for Draft

- .circleci/config.yml
As seen at https://circleci.com/gh/Azure/draft/15.
> fix DOCKER_USERNAME typo

- CHANGELOG.md
(cherry picked from commit 0054537f5fe2561f8dc0fe3cca0fc5970f62562d)
> add v0.7.0 CHANGELOG

- examples/python/app.py
- examples/ruby/Gemfile
- examples/ruby/Gemfile.lock
- examples/ruby/app.rb
This PR took WAY longer than it needed to. Basically it looks to see if we $KUBERNETES_SERVICE_HOST is present, and if so, disable logging from any requests coming from Kubernetes that is identified with the user agent `Go-http-client/1.1`.
I wish we could be more specific on the incoming requests, but it doesn't seem like that's possible.
closes https://github.com/Azure/draft/issues/328
> do not log requests from kubernetes liveness/readiness probes for python/ruby apps

- docs/ingress.md
If you are not familiar with the base domain, there is nowhere stated that you must pass the `--ingress-enabled` flag to configure the ingress.
> Clarify how to configure the base domain

- glide.lock
- glide.yaml
linguist forked git4go which points to the same fix I made in my fork.
All builds in master are currently breaking due to upstream churn in shibukawa's repository; this fixes things (for now).
> fix git4go dependency

- cmd/draft/init.go
- cmd/draft/installer/config/config.go
- cmd/draft/installer/install.go
> feat(cmd/draft): add flag to override draftd image

- cmd/draft/delete.go
- cmd/draft/delete_test.go
- cmd/draft/draft.go
- cmd/draft/testdata/delete/src/simple-go-error/main.go
This implementation of `draft delete` calls helm from the draft client. We should really be calling delete from the server, so this is a temporary implementation. The interface/experience should not change but it makes more sense to call delete from server after #379 is in place which gives us the ability to query if an application exists.
> feat(cmd/draft): implement draft delete

- pkg/rpc/server.go
Increasing this limit until chunking strategy is devised.
> bump max rpc message size to 40 MB

- examples/python/app.py
- examples/ruby/Gemfile
- examples/ruby/Gemfile.lock
- examples/ruby/app.rb
This reverts commit 6c597766c60224f9a7ee50af24476869f62b2a09.
This is no longer necessary now that #377 has been merged. :D
> Revert "do not log requests from kubernetes liveness/readiness probes"

- packs/ruby/Dockerfile
- packs/ruby/chart/values.yaml
> switch default port to 3000 for Ruby apps

- docs/pack-repositories.md
> add "How to create and maintain a pack repository"

- cmd/draft/delete_test.go
- cmd/draft/init.go
- pkg/draft/local/local.go
> ref(draft): fix lint errors

- cmd/draft/delete.go
- cmd/draft/draft.go
- cmd/draft/init.go
- cmd/draft/installer/install.go
- pkg/draftd/portforwarder/portforwarder.go
This allows `draft` to communicate with Draftd installed in a different namespace than kube-system. This will also install Draftd in that same namespace so it may be installed with Tiller in that same namespace. Users can use `export DRAFT_NAMESPACE=foo` so they don't have to always specify it every time.
closes #357
> add global flag `--draft-namespace`

- .circleci/config.yml
- docs/contributing/release-checklist.md
CircleCI recently changed how tags are being triggered and have now switched over to shutting off tag builds by default.
As per https://circleci.com/docs/2.0/configuration-reference/#tags
> 1. For a branch push unaffected by any filters, CircleCI runs the job.
> 2. For a tag push unaffected by any filters, CircleCI skips the job.
> Item two above means that a job must have a `filters` `tags` section to run as a part of a tag push and all its transitively dependent jobs must also have a `filters` `tags` section.
> use CircleCI's Workflow feature

- docs/contributing/release-checklist.md
In general, it is bad practice to rewrite commit history especially on a publicly-facing branch. It makes more sense to keep rolling with the changes.
> remove notes about amending commits on release branch

- .circleci/config.yml
without it, the `filters` field is being parsed at the jobs level.
> add another indentation level

- docs/install.md
due to #406 we should drop Windows from the install guide. We'll continue to build and release Windows binaries, but given its current state we shouldn't "support" it until we can fix these showstoppers.
> drop Windows support from install guide

- cmd/draft/delete.go
We want to free up the application name for future use when calling `draft delete`.
> purge release on delete

- .circleci/config.yml
In circle builds, glide is detecting GLIDE_HOME as the current workspace instead of /root/.glide. Hardcoding $GLIDE_HOME makes it such that glide respects $HOME.
Running a circle build with SSH enabled showed the following:
```
root@bd257551223a:/go/src/github.com/Azure/draft# glide | grep GLIDE_HOME
--home value            The location of Glide files (default: "/go/src/github.com/Azure/draft/.glide") [$GLIDE_HOME]
root@bd257551223a:/go/src/github.com/Azure/draft# git status
Untracked files:
(use "git add <file>..." to include in what will be committed)
.glide/
nothing added to commit but untracked files present (use "git add" to track)
```
This is causing release candidates to be released with a dirty git tree state.
```
><> draft version
Client: &version.Version{SemVer:"v0.8.0-rc3", …
```
> fix dirty git tree state in circle builds

- cmd/draft/init.go
This flag goes through all the steps without actually installing anything. It's useful when used along with `--debug` for debugging purposes.
> add --dry-run flag to `draft init`

- docs/install.md
A 10 minute video on how to deploy Draft to Azure Container Services.
> Video: Deploying Draft on Azure Container Services

- packs/ruby/.dockerignore
tmp/ is commonly known as a temporary directory that should not be added
to the Docker image for Rails apps.
closes #337
> add tmp/ to default .dockerignore for Ruby

- pkg/draft/pack/repo/installer/local_installer.go
- pkg/draft/pack/repo/installer/vcs_installer.go
- pkg/osutil/osutil.go
- pkg/osutil/osutil_test.go
- pkg/plugin/installer/base.go
This function attempts to create a symbolic link, but falls back to os.Rename() when the user does not have permission to create symbolic links (e.g. Windows non-administrators).
closes #401
> implement SymlinkWithFallback

- packs/javascript/Dockerfile
I am not sure if this has to be default pack or e.g. `javascript-edge`
> Bump docker image to node 8.8 to support async etc

- charts/draftd/templates/deployment.yaml
- cmd/draft/installer/install.go
The latest version of minikube now supports Docker 17.06.0-ce which contains the multi-stage build feature in Docker, therefore removing the need to run a separate docker engine just for builds. #163 was introduced strictly for this feature, so it's no longer required.
As an added bonus, we get:
- automatic authentication to Azure Container Registries in the same resource group, and automatic authentication to the minikube docker registry (winner winner chicken dinner)
- free security updates to docker (big maintenance win)
closes #430 
closes #431 
closes #405 
partially addresses #213
#355 and #285 should be closed assuming that GKE/AWS clusters are automatically authenticated against GCR/ECR instances, but that needs verification.
> remove docker-in-docker container

- cmd/draft/testdata/create/generated/empty/charts/go/values.yaml
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/charts/go/values.yaml
- cmd/draft/testdata/create/generated/simple-go/charts/go/values.yaml
- cmd/draft/testdata/drafthome/packs/github.com/Azure/draft/packs/go/charts/values.yaml
- packs/csharp/charts/values.yaml
- packs/go/charts/values.yaml
- packs/gradle/charts/values.yaml
- packs/java/charts/values.yaml
- packs/javascript/charts/values.yaml
- packs/php/charts/values.yaml
- packs/python/charts/values.yaml
- packs/ruby/charts/values.yaml
For the new pack developer, it's not known that these values are overwritten on `draft up`. Removing these will make it easier for new pack devs to approach pack development.
> remove redundant/confusing default values in packs

- examples/example-ruby/app.rb
Hello,
i noticed that the port set in the ruby example is not aligned with the port in the ruby pack.
The connection gets refused out of the box
I adjusted the file `app.rb` to reflect the port set in the dockerfile https://github.com/Azure/draft/blob/10065c94086dca145a7b0e2ffcc37e93a0ba0d36/packs/ruby/Dockerfile#L3
With the change it works
> Fix ruby example: Wrong port in app.rb

- docs/install-advanced.md
- docs/install.md
closes #403 
closes #358 
NOTE: have not tested this yet.
> add rbac/namespacing docs

- examples/example-swift/.gitattributes
- examples/example-swift/Package.pins
- examples/example-swift/Package.swift
- examples/example-swift/Sources/main.swift
- packs/swift/.dockerignore
- packs/swift/Dockerfile
- packs/swift/chart/.helmignore
- packs/swift/chart/Chart.yaml
- packs/swift/chart/templates/NOTES.txt
- packs/swift/chart/templates/_helpers.tpl
- packs/swift/chart/templates/deployment.yaml
- packs/swift/chart/templates/ingress.yaml
- packs/swift/chart/templates/service.yaml
- packs/swift/chart/values.yaml
supercedes #155
closes #96
blocked until #344 is merged, as without it the example swift app is improperly determined as a different programming language.
> Add swift support

- cmd/draft/draft.go
- cmd/draft/init.go
- cmd/draft/installer/config/config.go
- cmd/draft/installer/install.go
- cmd/draftd/draftd.go
- cmd/draftd/start.go
- docs/draft_ssl.md
- pkg/draft/client.go
- pkg/draft/server.go
- pkg/rpc/client.go
- pkg/rpc/option.go
- pkg/rpc/server.go
Enable TLS for gRPC communication between draft client and server.
> feat/tls: enable draft/draftd TLS

- CHANGELOG.md
(cherry picked from commit d60ad977145c744294f21039a562d9e1fb5a5221)
> add v0.9.0 CHANGELOG

- glide.lock
- glide.yaml
Fixes `glide install` on new machines.
> fix(glide): alias Sirupsen/logrus repo to github.com/sirupsen/logrus

- packs/java/.dockerignore
to reduce the amount of data tarred up and POSTed to docker when building the docker image via the  command
> ignore common java work directories

- pkg/plugin/builtins.go
Fixes issue where we keep downloading pack-repo even if we have right version.
> ref(pkg/plugin): remove 'v' from pack-repo ver

- cmd/draft/connect.go
- cmd/draft/delete.go
- cmd/draft/environment.go
- cmd/draft/environment_test.go
- cmd/draft/up.go
- pkg/draft/local/local.go
This PR adds the possibility to choose the environment through the --environment / -e flag in connect.
Since this is possible with "up", i would expect this from connect as well.
There are two issues with the current implementation:
- Not having the default "development" environment in the .toml config results in a panic when calling "draft connect", because draft falls back to the default "development" and reads it from the map - and afterwards accesses the nil return value. See here https://github.com/birdayz/draft/commit/22fbcaa020f2bdae3351f83c82bd212b265274d1#diff-19de32b90b575e618c86ae2c9c8a80d6L49
Fixed by this PR. 
- It is only possible to choose the environment in connect by setting the environment variable DRAFT_ENV. Since up allows the -e param, i added this to connect as well. …
> Add environment selection flag to connect command

- .circleci/deploy-azure.sh
this should fix up the latest CircleCI failure because we're on an older release of azure-cli. 2.0.23 is the latest release.
> install the latest 2.x release of azure-cli

- .circleci/deploy-azure.sh
Currently azure-cli is failing to upload assets to blob storage because it's missing opensslv.h. Installing libssl-dev and re-compiling pyOpenSSL with a newer version of libssl-dev fixes this.
Tested manually by re-running the latest job on master and installing libssl-dev/recompiling pyOpenSSL.
> install libssl-dev

- charts/draftd/templates/deployment.yaml
- cmd/draft/installer/templates.go
https://github.com/kubernetes/minikube/pull/2077 changed the default service cluster IP range to 10.96.0.0/12 from 10.0.0.0/24.
Without this fix, `draft up` on minikube will fail with the following error:
> buildApp: pushImg error: Get https://10.107.109.2/v1/_ping: dial tcp 10.107.109.2:443: i/o timeout
> Update --insecure-registry CIDR range

- packs/java/Dockerfile
`mvn` invocation should be non interactive (`--batch-mode`). Fix  #524
> java pack: `mvn` invocation should be non interactive (`--batch-mode`). Fix  #524

- packs/gradle/Dockerfile
- packs/java/Dockerfile
Use the Debian based Docker image instead of the Alpine image due to bugs with the JDK on Alpine. Fix #526
> Use the Debian based Docker image instead of the Alpine image

- cmd/draft/connect.go
- cmd/draft/logs.go
- pkg/draft/local/local.go
- pkg/draft/local/local_test.go
What this does:
- adds `draft connect -c` flag
- if a container is specified, start a tunnel to the container's first port and get logs from that container
- if no container is specified, start tunnels to the first port of all containers in pod and get logs from all containers
> Add draft connect --container/-c flag (#399)

- cmd/draft/connect.go
- pkg/draft/local/local.go
- pkg/draft/local/local_test.go
- fixes #535 
- starts tunnel to every `containerPort` in pod spec
Essentially, when doing `draft connect` with the deployment below, you get:
```
<tunnels to all ports of all containers>
Connect to multi-port:80 on localhost:53010
Connect to multi-port:81 on localhost:53012
Connect to go:8080 on localhost:53014
<logs from all containers, including ones without ports>
``` 
The `--container/-c` flag works as expected, creating tunnels only for all the ports of the selected container.
Best tried with the following deployment template, which has containers with 0, 1 or 2 defined `containerPort`
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: {{ template "fullname" . }}
labels:
draft: {{ default "draft-app" .Values.draft }}
chart: "{{ .Chart.Name }}-{{ .Chart.Version | …
```
> Connect to every containerPort in pod

- cmd/draft/draft.go
- cmd/draft/ensure.go
This way, draft commands can use the same rootCmd when adding plugins to the command tree, performing command lookups or re-loading rootCmd after `draft init`.
> add rootCmd variable

- Makefile
- pkg/rpc/Makefile
- scripts/setup-protobuf-include.sh
Fixes #555 
(It first needs a `make bootstrap` to execute `scripts/setup-protobuf-include.sh`, which brings the `include` directory from protobuf in `vendor`)
> Fix make rpc target by adding local protobuf include in vendor

- cmd/draft/draft.go
Per PR #3082 which closed helm issue#2658., we should use 127.0.0.1 instead of localhost to fix ipv6 lookup error: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = “transport: dial tcp [::1]:56463: getsockopt: connection refused”; Reconnecting to {localhost:56463 <nil>}
> Fix for ipv6 lookup error

- cmd/draft/connect.go
- pkg/draft/local/local.go
- pkg/draft/local/local_test.go
- pkg/draft/tunnel/tunnel.go
- pkg/draftd/portforwarder/portforwarder.go
This PR adds the ability to specify local ports, by doing  `draft connect -p <local>:<remote> -p <local>:remote`
> Add local port forwarding for draft connect

- cmd/draft/connect.go
- cmd/draft/testdata/create/generated/empty/draft.toml
- cmd/draft/testdata/create/generated/html-but-actually-go/draft.toml
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/draft.toml
- cmd/draft/testdata/create/generated/simple-go/draft.toml
- cmd/draft/up.go
- docs/getting-started.md
- docs/reference/dep-006.md
- pkg/build/build.go
- pkg/draft/local/local.go
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
- pkg/draft/testdata/app/draft.toml
This PR:
- switches underscores for dashes for `draft.toml`, as discussed in Slack
- adds an `override-ports` flag in `draft.toml`
Thanks!
>  Add override-ports flag and use dashes instead of underscores in draft.toml

- pkg/draft/context.go
SHA1 has been proven to be broken by providing two PDFs with differing content that will output the same hash. It was also deprecated in 2011. Using sha256 instead provides the same functionality with a stronger hashing algorithm.
> use the sha256 hash algorithm

- pkg/draft/local/local.go
- pkg/kube/podutil/podutil.go
- pkg/kube/podutil/stop.go
This PR fixes #329 
- can someone with an available Minikube test it? At some point @michelleN did some testing and got some timeout errors - I haven't seen any issues on AKS so far
> Wait for pod to be ready before connecting

- pkg/builder/builder.go
- pkg/draft/manifest/load.go
This function accepts a path and opens the file for reading. If successful, it will output the loaded manifest configuration.
should probably wait until #573 is merged since this will be easier to rebase and this doesn't introduce anything; just code cleanup
> add manifest.Load()

- cmd/draft/up.go
Because of https://github.com/spf13/cobra/issues/216, since `draft up` has its own  `PersistentPreRun`, the `rootCmd` `PersistentPreRunE` from `draft.go` is no longer called - which means (among others) that the global config is not loaded.
This adds a call to the  the `rootCmd` `PersistentPreRunE`.
cc @bacongobbler
> Fix root command's pre run not being called

- docs/install.md
this formula was removed in https://github.com/Azure/homebrew-draft/pull/4 due to issues like #532.
> remove draft-canary reference

- cmd/draft/connect.go
- cmd/draft/testdata/create/generated/empty/draft.toml
- cmd/draft/testdata/create/generated/html-but-actually-go/draft.toml
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/draft.toml
- cmd/draft/testdata/create/generated/simple-go/draft.toml
- cmd/draft/up.go
- packs/clojure/charts/templates/deployment.yaml
- packs/csharp/charts/templates/deployment.yaml
- packs/go/charts/templates/deployment.yaml
- packs/gradle/charts/templates/deployment.yaml
- packs/java/charts/templates/deployment.yaml
- packs/javascript/charts/templates/deployment.yaml
- packs/php/charts/templates/deployment.yaml
- packs/python/charts/templates/deployment.yaml
- packs/ruby/charts/templates/deployment.yaml
- packs/swift/charts/templates/deployment.yaml
- pkg/builder/builder.go
- pkg/draft/local/local.go
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
- pkg/kube/podutil/podutil.go
This PR adds the `draft up --auto-connect` flag and entry in manifest.
In order to ignore existing running pods with the previous version, this PR also injects the build ID as label on the pods and takes it into consideration when connecting.
> Auto connect for draft up

- cmd/draft/logs.go
Most of the times you need to see the logs of the latest build - this PR adds the latest build ID by default to the logs cmd - if you know a previous build ID you can pass it as the first argument.
Now you simply do `draft logs` and by default you get the latest build logs.
> Simplify draft logs cmd

- Makefile
This caused CI to fail to release v0.12.0-rc1 due to the workflow of `make clean build-cross` as part of [`.circleci/deploy-azure.sh`](https://github.com/Azure/draft/blob/c7c7d08721328cf84a792b23affb1476080f510e/.circleci/deploy-azure.sh#L34-L36).
Reverts Azure/draft#596
> Revert "add vendor to `make clean`"

- pkg/draft/pack/repo/installer/vcs_installer.go
Should fix #587 - tested in Windows and WSL
In order to test you need to:
- clone https://github.com/Azure/draft-pack-repo
- `dep ensure` and delete `vendor/github.com/Azure/draft` so it uses the one in the GOPATH (so this branch)
- `go build` 
- copy the executable in `$DRAFT_HOME/packs/draft-pack-repo/bin`
- `draft pack-repo add <pack-repo-url>` should successfully work (both in user and admin)
Please test this also with macOS and regular Linux.
On with #396!
> Fix pack-repo add on Windows

- cmd/draft/connect.go
How to test this:
- delete logs in `~/.draft/logs`
- try running `draft connect` or `draft logs`
Instead of a panic, you should now get an error.
> Avoid panic for draft connect and logs when there is no build in logs

- docs/getting-started.md
- docs/install-advanced.md
- docs/install.md
This documents the new-and-improved setup process to use Draft with and without a container registry.
> document container registry setup for Minikube and AKS

- cmd/draft/connect.go
This fixes the `Your connection is still active` message being passed first time when connecting.
#624
> Fix inaccurate connection message order

- cmd/draft/connect.go
This flag is used by external tools to know when a pod of the application is running.
> Add --dry-run flag to draft connect

- docs/install-advanced.md
- pkg/builder/builder.go
- pkg/builder/registry.go
- pkg/builder/registry_test.go
This enables use cases like deploying to an AKS cluster with a private third party registry such as quay.io. This is the same behaviour as draftd used to work in previous releases. I removed it in #573 because I thought all the use cases we were seeing involved a level of trust between the cluster and the registry, but that is not always the case.
This feature is only enabled if the user opts into setting a registry via `draft config set registry`. It performs a lookup in `~/.docker/config` to fetch the config, then injects that into the cluster via an image pull secret.
> re-instate injecting the image pull secret into the namespace

- pkg/draft/pack/load.go
- pkg/draft/pack/load_test.go
- pkg/draft/pack/testdata/pack-python/README.md
> ref(pkg/draft): skip copying pack readme on create

- pkg/builder/builder.go
Remove `AsMap()` so that map doesn't get cloned.
Closes #223
> fix(client): avoid cloning map

- cmd/draft/plugin.go
- cmd/draft/plugin_test.go
This way, install hooks invoked via `draft plugin install` know which version of the plugin to install.
relates to #627. After this, we need to give draft-pack-repo knowledge of this envvar.
> inject plugin version into the plugin environment

- cmd/draft/connect.go
- cmd/draft/ensure.go
- cmd/draft/logs.go
- pkg/builder/builder.go
- pkg/osutil/osutil.go
Issue context in https://github.com/Azure/draft/issues/618#issuecomment-380512278
To test:
- delete `$DRAFT_HOME/logs`
- now if you build multiple applications, their logs should be in `$DRAFT_HOME/logs/app-name`
- `draft connect` and `draft logs` should respect the current directory and app (and not just connect / get logs for the latest app built and released)
Also added a couple of helper methods in `osutil` - to test, execute `draft init` again (as they ensure directories and files).
> Group build logs in directory for each app

- docs/reference/dep-006.md
- examples/example-go/main.go
- pkg/builder/builder.go
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
This PR adds support for custom image tags.
To test, build this branch and add the following config in `draft.toml`:
```
custom-tags = ["latest", "your-custom-tag"]
```
The tags `latest` and `your-custom-tag` will be pushed to the container registry, as well as the auto-generated SHA tag that is currently pushed by Draft.
> Support for custom image tags

- docs/reference/dep-006.md
The formatting on <local-port>:<remote-port> is being interpreted as an
HTML-like tag in GitHub's markdown renderer. This changes it to all caps
like an env var.
I also tried to make it slightly clearer that the first port was the one
on localhost, and the second was the one for the container. Earlier, I
got confused and interpreted "local" as "the port local to the binary"
and "remote" as "the tunnel".
> docs(dep-006): fix formatting

- Gopkg.lock
- Gopkg.toml
The following removed lines where unnecessary since they are in
Gopkg.lock and causing error output when running `dep ensure`:
```
$ dep ensure
dep: WARNING: branch, version, revision, or source should be provided for "github.com/BurntSushi/toml"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/Masterminds/semver"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/fatih/color"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/protobuf"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/gosuri/uitable"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/oklog/ulid"
dep: WARNING: branch, version, revision, or …
```
> Gopkg.toml: remove errors when running `dep ensure`

- cmd/draft/testdata/create/generated/empty/draft.toml
- cmd/draft/testdata/create/generated/html-but-actually-go/draft.toml
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/draft.toml
- cmd/draft/testdata/create/generated/simple-go/draft.toml
- docs/reference/dep-006.md
- examples/example-go/main.go
- pkg/builder/builder.go
- pkg/builder/builder_test.go
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
This PR adds the ability to specify the Dockerfile and chart used for a specific environment in `draft.toml`.
To test:
- `git clone https://github.com/radu-matei/draft-env-sample`
- `draft up` - this will `up` the default environment, using `Dockerfile` and the `javascript` chart
- `draft connect` - will connect only to port 8080
- `draft up --environment debug` - this will `up` the debug environment, using `Dockerfile.debug` and the `node-debug` chart
- `draft connect --environment debug` - will connect only to ports 8080 and 9229
Also make sure to try with a clean `draft create` and `draft up`.
> Add Dockerfile and chart as environment

- pkg/plugin/builtins.go
> bump pack-repo to 0.4.1

- .gitignore
I'm finding these files pulled in from the draft pack when using the example-python app. Adding these to .gitignore so I don't accidentally commit these files to the example apps.
> add .dockerignore and .draft-tasks.toml to gitignore

- cmd/draft/connect.go
- cmd/draft/connect_unix.go
- cmd/draft/connect_windows.go
Running `draft connect --detach` will reexecute draft with `draft connect --export`. `--export` is a hidden flag and is meant to only be used by draft if invoked with `--detach`. `--export` instructs draft to dump the environment information for connection. Container logs are lost in the detached state.
Draft does not cleanup the detached process. The onus of cleanup is on the detacher, because draft is not a process manager. Re-running `draft connect --detach` will establish a new background draft tunnel.
Usecase:
```
/> eval $(draft connect --detach)
/> curl $EXAMPLE_GO_GO_SERVICE_HOST:$EXAMPLE_GO_GO_SERVICE_PORT
Hello World, I'm Golang!
```
> enable detaching from draft connect

- Makefile
- scripts/setup-protobuf-include.sh
Now that we don't have a server-side component, we can get rid of the setup script for the protocol buffers.
> Remove protobuf setup from Makefile

- pkg/builder/azure/builder.go
- pkg/builder/azure/builder_test.go
Trim works with a cutset, i.e. all single characters contained in the cutset are
removed. This leads to unexpected and wrong behavior, since getRegistryName
should only remove a specific string contained in its given input.
Fixes #712
> use strings.Replace instead of strings.Trim in getRegistryName

- pkg/cmdline/cmdline.go
When running `draft up` on Windows under `cmd` or `powershell`, the colourisation escape sequences are not interpreted but just printed to the screen, resulting in confusing noise around the Draft progress messages.  This PR suppresses colourisation on Windows, making messages more readable.
It would be good to detect Windows shells which are capable of handling escape sequences, e.g. `cmder` or `hyper` - this is a first step that addresses what I think is going to be the most common case for Draft on Windows.  It can be refined if required by improving the `cmdline.consoleSupportsColor()` function over time.
> Suppress colorization when it would result in escape sequence noise

- pkg/builder/azure/builder.go
- pkg/builder/azure/builder_test.go
`strings.TrimSuffix` is a safer option than `strings.Replace` for this operation. This might also fix a bug where a registry name such as "usdraftacr.azurecr.io" is getting trimmed down to "sdraft".
> use strings.TrimSuffix instead of strings.Replace

- docs/quickstart.md
> Add Chocolatey and GoFish to the quickstart docs

- cmd/draft/connect.go
because the `if` block ends with a return statement, the `else` block isn't necessary.
This lowers the Cyclomatic complexity of the given block of code.
> fix linter suggestion

- docs/reference/dep-006.md
- pkg/builder/builder.go
This PR enables specifying a local path for your charts (other than `charts/`).
To test this, place your chart in a directory other than `charts/`, then in `draft.toml` specify the relative path to the chart you want to release - for example: `charts = "deploy/javascript"`.
The default behaviour is persisted - if nothing was specified in the environment, Draft will try to deploy the first directory in `charts/`.
Please note that this PR opens the possibility to release a chart from upper levels, allowing scenarios where you have all charts for your services in another folder.
closes #739
> Allow charts in other directories

- Gopkg.lock
Addresses https://github.com/Azure/draft/issues/774
Version of rjeczalik/notify was causing linting and build errors.
> update rjeczalik/notify dependency to address #774

- docs/contributing/hacking.md
upx is no longer used in the Makefile to compress binaries.
> remove upx from hacking docs

- docs/reference/dep-006.md
- pkg/builder/azure/builder.go
- pkg/builder/docker/builder.go
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
This PR adds build arguments for the Docker builder.
To test it: 
- add the following in `draft.toml`:
```
image-build-args = { BUILD_TIME_ARG = "build-time-argument-value",  HTTP_PROXY = "http://my-proxy" }
```
- use the arguments in your Dockerfile:
```
ARG BUILD_TIME_ARG
RUN echo $BUILD_TIME_ARG
ARG HTTP_PROXY
RUN echo $HTTP_PROXY
```
Here are the [best practices for Docker build arguments](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg), linked in the dep here.
closes #663
> Implement image build arguments container builder

- .circleci/deploy-azure.sh
- Makefile
gox defaults to numCPU - 1 when cross-compiling, which on CircleCI this happens to be 31. By limiting to 3 parallel builds at one time, we prevent the issue of CircleCI running out of memory.
> WIP: Fix circle memory issues

- pkg/draft/pack/create.go
Addresses ChartName change to match current dir if appName not supplied.
```
example-go $ ../../bin/draft create
--> Draft detected Go (80.633803%)
--> Ready to sail
example-go $ tree -L 2
.
├── Dockerfile
├── charts
│   └── example-go
├── draft.toml
├── glide.yaml
└── main.go
2 directories, 4 files
```
Original concern here: https://github.com/Azure/draft/pull/784
> [Feature] use cwd for Chartname if appName not given

- cmd/draft/plugin_windows.go
- pkg/plugin/plugin.go
Refer to #715 
While reproducing this, i hit three problems:
1) Running the plugin - PrepareCommand tries to determine the executable by splitting with " " - in case of whitespace in path it will compute a wrong path for the executable. See my changes - i work around it by expanding the environment var after splitting, and not before. This is not super clean, but works.
2) At least for me, when the hook get.ps1 is called, on my Win10 VM, the window closes immediatly. This is due to the WindowStyle Hidden flag when calling powershell for the hook. It still works correctly, but it's strange if your cli window just disappears (and makes debugging a nightmare)
3) Downloading the default plugin pack - The install hook of the default plugin repo has to be adjusted, because powershell requires a …
> fix init on windows

- pkg/builder/builder.go
To test this:
- change the name of your Dockerfile in the directory and change that name in `draft.toml` - for example, using `example-go` from this repo:
```
[environments]
[environments.development]
name = "testing-golang"
namespace = "default"
custom-tags = ["latest", "canary"]
dockerfile = "Dockerfile.golang"
```
- run: `draft up examples/example-go` and everything should work as intented
Anyone around who can test on Windows before I do?
closes #720 
Thanks, @bacongobbler, for quickly identifying the issue!
> Fix wrong Dockerfile path when running draft up from another directory

- docs/quickstart.md
The link to Minikube was missing (due to malformed markdown), so this patch adds the link.
> Adding link to Minikube

- cmd/draft/up.go
Addresses issue from https://github.com/Azure/draft/issues/805 where 
> pre-up draft tasks happen after the environment and helm chart have been loaded in to memory, so it's not possible to download helm dependencies using helm dependency update a pre-up task and have them loaded with the rest of the chart and deployed. 
Discovered by @sam-doordash
> Reorder tasks and load during draft up

- cmd/draft/config.go
- cmd/draft/config_set.go
- cmd/draft/up.go
Provides additional feedback to users trying to use `draft config set`, by listing the known config keys or providing help on the value required for the selected config key.  The behaviour is now:
`draft config set`: Message now reads:
```
Error: This command needs a key and a value to set it to. Supported keys:
registry: Registry to push built containers to (e.g. docker.io/foo, foo.azurecr.io)
container-builder: How to build the container (supported values: docker, acrbuild)
... etc ...
```
`draft config set foo`: Message now reads `Error: This command needs a value: Registry to push built containers to (e.g. docker.io/foo, foo.azurecr.io)`.  If the key is not a known one, the second part of the message is instead `No help available for key 'foo'`.
These changes only affect the messages …
> Command-line documentation for draft config set

- docs/reference/dep-006.md
I wanted to be able to use a different service type and port number in different environments. I may debug on a clusterIP, but want to deploy to an external IP and port 80 for production. I couldn't find a clear explanation of how to use `set` so I added an explanation and samples.
> Adding example usage of set in draft.toml

- cmd/draft/testdata/create/generated/empty/draft.toml
- cmd/draft/testdata/create/generated/html-but-actually-go/draft.toml
- cmd/draft/testdata/create/generated/simple-go-with-draftignore/draft.toml
- cmd/draft/testdata/create/generated/simple-go/draft.toml
- pkg/draft/manifest/manifest.go
- pkg/draft/manifest/manifest_test.go
- pkg/draft/testdata/app/draft.toml
Fix #808 
This solution adds default value for dockerfile in draft.toml to Dockerfile.
> Using Dockerfile as default for dockerfile in draft.toml

- cmd/draft/config_set.go
Output error message instead of golang panic stacktrace.
Fixes #824
> Avoid panic when using config set before draft init

- packs/gradle/Dockerfile
Corrects docker image in the gradle pack.
Fixes in file permissions and the way the app is ran
> Packs: corrected gradle docker image

- docs/getting-started.md
- docs/reference/dep-003.md
As docker images used in bundled packs does not use onbuild images anymore, the docs should reflect that
Fixes #861
> Remove onbuild from docs

- docs/contributing/hacking.md
Fixes a dead link to the install-minikube.md guide which was previously named `install.md` and got renamed in #647.
> Fix dead link to installation guide and update helm repository link

- cmd/draft/up.go
- pkg/cmdline/cmdline.go
This PR adds the `--quiet` flag to the `up` command (fixes #386).
> Add quiet flag to up

- pkg/builder/builder.go
Ever since #798 was merged, omitting the name of the Dockerfile in `draft.toml` broke `draft up`.
This PR checks if the Dockerfile was set in `draft.toml`, and if not, sets it as the default Dockerfile - `Dockerfile`.
To test:
- in one of the examples in this repo do a `draft create`
- `draft up` - this should work now even if the `dockerfile` field in `draft.toml` is empty (`""`) or missing
- add the actual Dockerfile name (`Dockerfile`) in `draft.toml` and run `draft up` again - this should still work.
closes #869
> Add default Dockerfile name in builder

- .circleci/config.yml
This PR updates the Go version used in CircleCI to the latest current version (Go 1.11.1).
It also removes an unused reference to `DOCKER_USERNAME` (used in the past, when Draft used to have a cluster component).
closes #873
> Update CircleCI Go version

- CONTRIBUTING.md
- pkg/draft/pack/load.go
- pkg/draft/pack/load_test.go
- pkg/draft/pack/pack.go
- pkg/draft/pack/pack_test.go
This includes a major logic change and the appropriate tests. The big change: the Pack struct's File data is now of type map[string]PackFile instead of map[string]io.ReadCloser. This allows Pack to have both the data from a file, as well as its file permissions. Everything using Pack has been updated to use the new structure.
> Fix create permissions

- cmd/draft/init.go
This PR removes an unnecessary if condition to cleanup a golint warning.
Should be really straightforward.
> Fix golint warning: redundant if ...; err != nil check, just return error instead.

- pkg/draft/pack/repo/errors.go
- pkg/draft/pack/repo/installer/vcs_installer.go
I struggled for a while trying to figure out why I couldn't sync a new repo of Draft packs. The error sounded like I had a problem with my local setup - not the layout of the remote repo. This adds a new error code to clarify why things are failing when adding a new repo.
Before the change - it says I don't have a repo folder on my local machine. That would be accurate if I forgot `draft init`, but the folder is there.
```
draft pack-repo add https://github.com/PatrickLang/Windows-K8s-Samples
Installing pack repo from https://github.com/PatrickLang/Windows-K8s-Samples
Error: pack repo home "$(draft home)/packs" does not exist
Error: exit status 1
```
After the change - it shows an accurate error:
````
draft pack-repo add https://github.com/PatrickLang/Windows-K8s-Samples
Installing pack …
```
> Adding new error code to separate local repo from installer errors

- README.md
I've updated the brew install command to match https://github.com/Azure/homebrew-draft/blob/master/README.md.
See https://github.com/Azure/homebrew-draft/pull/10 for reference.
> Update brew install to match azure/homebrew-draft

- README.md
- docs/install-minikube.md
- docs/quickstart.md
I noticed [another repo][1] using this shorthand for a fully qualified install from a third party tap.
The [Homebrew docs][2] confirm that `brew tap ...` is redundant when running brew install with the fully qualified tap as this project already does.
I have tested this change as follows.
Uninstall:
```
$ brew uninstall azure/draft/draft
Uninstalling /usr/local/Cellar/draft/0.16.0... (5 files, 54.0MB)
$ brew untap azure/draft
Untapping azure/draft...
Untapped 1 formula (32 files, 29.4KB).
```
Verify:
```
$ brew tap | grep draft
$ brew list | grep draft
```
Install:
```
$ brew install azure/draft/draft
==> Tapping azure/draft
Cloning into '/usr/local/Homebrew/Library/Taps/azure/homebrew-draft'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: …
```
> Simplify brew install

- Gopkg.lock
- pkg/cmdline/cmdline.go
- pkg/cmdline/terminal_notwindows.go
- pkg/cmdline/terminal_windows.go
Color output on PowerShell needs to be explicitly enabled. Usually logrus does that, but only when printing a log message. To be on the safe side, do this explicitly during the CLI initialization. The implementation is based on how logrus does it.
> Enable color output on windows
