pkg/workflows/workflows.go
update the image tag for manifests. For kustomize and helm we use a production override which has the image modified however, we do not do this for regular k8s manifests. This PR changes that.
=> add default case in workflows.go

pkg/providers/azure.go, pkg/providers/providersutils.go
Following an error Karen and Quentin were experiencing with the setup-gh command, I was able to reproduce it and determined that it was caused by an update to the "az ad sp" and "az ad app" commands. They no longer return "objectId" in the json  response when you create, list or show them, instead they just return "id". That meant that the commands to assign roles and created FICs weren't working either because they rely on the sp and app "objectId"s
Changes:
- changed sp list to sp show since we really don't need to query a list to get one sp
- changed any queries for an "objectId" to an "id"
- removed the first sp exists check since new apps don't automatically have sp's
=> Updating AZ commands to work after upgrade

pkg/providers/providersutils.go
The updated error message added in #105  was incorrect for the check.  Changing the check to look for an empty subscription id returns the behavior to the previous and includes the improved error message.
=> fix subscription validation logic

cmd/update.go, pkg/logger/logger.go
small fixes to the logging formatter to correctly split stdout and stderr
=> Fix logger output split

README.md
This PR enables the visibility of key attributes this project has under the hood and the quality check in place.
It also benefit as one stop shop of all the test visibility and the failures as these badges will update in case of failure etc. 
I've also added the `go report` and `go docs` along with workflows in place.
Thanks heaps. ❤️🙏☕️ cc: @karenychen, @imiller31, @gambtho 
it will look shiny like this, along with other quality goodness which will come along and also when we improve the got-report it will move to A+
=> Add badges for CI and other key things visible upfront at repo level.

cmd/create.go, cmd/create_test.go, pkg/deployments/deployments.go, pkg/languages/languages.go, pkg/osutil/osutil.go
Introduce new `TemplateWriter` interface with the following methods:
```
WriteFile(string, []byte, os.FileMode) error
EnsureDirectory(string) error
```
This allows templates to be generated for arbitrary use cases independent of the local filesystem (ex: in-memory template generation)
Refactor dockerfile and deployment generation to use new interface, and added existing os filesystem write methods into the `LocalFSWriter` struct
Add `TemplateWrite` property to `CreateCommand` and set to the `LocalFSWriter` to maintain existing functionality
=> abstract filesystem and directory operations from templating logic

pkg/prompts/prompts.go
If the user does not provide a value for the last prompt for a given config, the default value is not set for that variable. 
Minimal Repro:
```
pip install Django
django-admin startproject mysite && cd mysite
draft create --dockerfile-only
```
Actual Behavior:
Dockerfile starts with `FROM python:`
Expected behavior:
Dockerfile starts with `FROM python:3`.
=> [fix] Ensure last prompt gets default value

.github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, cmd/create.go, cmd/update.go, pkg/addons/addons.go, pkg/config/addon_config.go, pkg/filematches/filematches.go, pkg/prompts/prompts.go, test/check_windows_addon_helm.ps1, test/check_windows_addon_kustomize.ps1, test/gen_integration.sh, test/integration/rust/helm.yaml, test/integration/rust/kustomize.yaml, test/integration/rust/manifest.yaml, test/integration_config.json
The following PR adds a `--variable` flag for the `draft update` command, which makes it possible to run the command non-interactively.
This makes adding integration tests possible for the command, which this PR also adds.
Integration tests have been added for the `update command`
Integration tests have been added for the `draft update` command for every existing integration scenario.
For linux helm and kustomize, the upgrade integration test was added to the existing integration …
=> add `--variable` flag to `draft update` command

cmd/create.go, pkg/config/draftconfig.go, pkg/prompts/prompts.go, template/deployments/helm/charts/templates/deployment.yaml, template/deployments/helm/charts/templates/namespace.yaml, template/deployments/helm/charts/templates/service.yaml, template/deployments/helm/charts/values.yaml, template/deployments/helm/draft.yaml, template/deployments/kustomize/base/deployment.yaml, template/deployments/kustomize/base/namespace.yaml, template/deployments/kustomize/base/service.yaml, template/deployments/kustomize/draft.yaml, template/deployments/kustomize/overlays/production/deployment.yaml, template/deployments/kustomize/overlays/production/kustomization.yaml, template/deployments/kustomize/overlays/production/service.yaml, template/deployments/manifests/draft.yaml, template/deployments/manifests/manifests/deployment.yaml, template/deployments/manifests/manifests/service.yaml
add builderVarDefault support for a referenceVar field that allows the default for a prompt to be a previously supplied value from a previous prompt in the same series of prompts.
add namespace support across the deployment templates instead of just using the APPNAME or the default namespace every time
=> add referenceVar default support and namespace

scripts/install.sh
This PR enables the `DRAFT CLI Installer` which means user no longer need to go download the cli binary based on their operating system, that all can be taken care of by this.
This enhancement will also take care of https://github.com/Azure/draft/issues/143 which asks for `JQ processor installation`. 🎊🚀🥷
As we develop: this just need minor readme update. like cli location will be `usr/local/bin/...` and its easily callable. cc: @qpetraroia thanks. (Also for windows user Installation a note like various other tools that - `Windows isn't currently supported (you can use WSL)`)
Thank you so much all. ❤️☕️🚀 **cc**: @bfoley13, @hsubramanianaks , @davidgamero , @qpetraroia, @sabbour  **fyi**:  @gambtho 
**Simple usage will looks like:**
```*.sh
curl -fsSL …
```
=> Enable draft installer

.github/workflows/release-and-publish.yml
- Automatically run the release and publish workflow using the `path` field on the `push` trigger for the workflow
- Also allows the most recent release description to be updated by simply updating the CHANGELOG.md without re-releasing binaries
- More closely follow the CHANGELOG is the single source of truth
https://github.com/davidgamero/draft/actions/runs/3244275984/jobs/5320229671
=> Auto run changelog release

pkg/deployments/deployments.go, pkg/languages/languages.go
a couple sections of the deployment and dockerfile generation use hard-coded strings to create paths with string formatting, with causes issues with the root directory as a target.
=> replace hard coded path joins with path.join

CHANGELOG.md
- The new `draft info` command from #157 prints supported language and field information in json format.
- An integration test was added for the installation shell script to better ensure that the script works as expected.
- File path output for root locations had a bug with string-formatted paths. The `path.Join` method has been substituted to fix this.
- Remaining uses of the `viper` library have been migrated to `gopkg.in/yaml.v3` for consistency.
- Unused files in the `web` package have been removed.
- Minor reorganization across the `config` and `addons` packages to reduce the number of exported functions and types.
Release
=> release for draft info and other fixes

README.md
This PR fixes the Readme Badge for this tool. Currently in main it is appearing as missing image because the workflow was old and removed.
I noticed this while helping for a release. Thanks. ☕️❤️🙏 
Please refer to the screenshot below and compare with current `main` version:
=> Fix badge for release.

.github/workflows/release-and-publish.yml
This PR is open to cater the needs for this following PR https://github.com/Azure/draft/pull/158 contribution from user @mukunku, fyi to @davidgamero if both of you please take a look, seemed simple and from comment it seems like I can help for the verification/code-sign part. Thanks heaps! ❤️☕️🙏
I checked the difference and release note for action used and it only contained the node version bump - https://github.com/mukunku/tag-exists-action/releases/tag/v1.1.0 
Please refer to #158 
=> fix action version.

.gitignore, pkg/prompts/prompts.go, pkg/prompts/prompts_test.go
Fixes a current bug where variable defaults are not resolved properly for references
Added unit tests for prompting logic and default resolution to avoid this issue in the future
Refactor prompt package to allow better testing by adding parameters for Stdin and Stdout with defaults on nil to follow `promptui` library convention
Remove deprecated overridestring structs
=> Fix variable defaulting resolution bug/ remove deprecated overridestring/ enhance testing

.github/workflows/codeql-analysis.yml
[codeql v1 is deprecated](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated), and we need to bump to v2
=> bump codeql since v1 is deprecated

.github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, test/gen_integration.sh
github action jobs must be listed by name to be required for PRs to merge, and since we have over 100 in draft across all of the languages and deployment types we can't list them all in a branch protection rule.
creating a new job that needs all of the other jobs would allow us to require just the new "summary" job, blocking PRs until every step has passed.
currently, PRs can be merged while integrations are running as long as approvals are in, even if the tests haven't finished as long as they haven't failed.
=> helm and kustomize aggregate summary steps

pkg/addons/addons_test.go, pkg/languages/languages_test.go, pkg/osutil/osutil.go, pkg/osutil/osutil_test.go, pkg/templatewriter/writers/filemapwriter_test.go
When executing a variable substitution via CopyDir, an error should be thrown if a variable is not supplied but exists in the templates.
Doing this validation at a lower level in the os package allows us to gain this protection across all the commands
=> error on unsubstituted vars

Dockerfile, pkg/addons/addons.go, pkg/config/draftconfig.go, pkg/prompts/prompts.go, pkg/prompts/prompts_test.go
Add a new boolean field to BuilderVars that allow prompting to be skipped, in which case the default value will be used. The var can still be overridden with a flag since that occurs outside the prompting logic which triggers a skip.
Since this adds a new boolean field, it defaults to false allowing backwards compatibility with all existing templates
=> no prompt support for buildervars

Makefile, pkg/workflows/service_types.go, pkg/workflows/workflows.go, pkg/workflows/workflows_test.go, template/deployments/helm/charts/production.yaml, template/deployments/helm/charts/templates/deployment.yaml, template/deployments/helm/charts/values.yaml, template/deployments/helm/draft.yaml, template/deployments/kustomize/base/deployment.yaml, template/deployments/kustomize/draft.yaml, template/deployments/kustomize/overlays/production/deployment.yaml, template/deployments/manifests/draft.yaml, template/deployments/manifests/manifests/deployment.yaml, test/skaffold.yaml, test/templates/helm/charts/production.yaml, test/templates/helm/charts/templates/deployment.yaml, test/templates/helm/charts/values.yaml, test/templates/helm_prod_values.yaml
The recommended generated key names in draft don't line up with the  keys in the starter workflows, so this PR changes the `imageKey` key to just `image` so that they are all consistent
This is a breaking change for consumers of the `IMAGENAME` variable, as it will no longer can contain both an image name and tag. 
Previously, `alpine:latest` was a valid `IMAGENAME`, but now the `IMAGETAG` variable (which defaults to "latest" following docker and kubernetes convention) should be used to pass a tag.
Usages of `IMAGENAME` that include a tag will now need to use the `IMAGETAG` variable for passing a tag, as passing an image name like `alpine:latest` will result in double-tagging such as `alpine:latest:latest` 
Please describe the tests that you ran to verify your changes. Provide …
=> rename helm `imageKey` to `image` to match starter workflows

CHANGELOG.md
**BREAKING** changes to `IMAGE` variable
- New, optional `disablePrompt` property on Builder Variables in draft config (#180):
- Default Value: `false` 
- Variables with `disablePrompt: true` will not be prompted for when running `draft interactive commands`
- Variables with `disablePrompt: true` can still be supplied via flags (`draft create --var TAG=latest`) or draft config files
- Example Usage:
```
variables:
- name: "TAG"
description: "the tag of the image to be built"
disablePrompt: true #  New optional field that is used to disable the prompt for this variable
...
```
- For all draft substitutions, draft will now error if unsubstituted variables are found in the final output (#175)
- **BREAKING** the `IMAGE` variable no longer can include an image tag. The `TAG` variable should be …
=> release 0.0.28 notes

.github/workflows/e2e-info.yml, .github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, .github/workflows/unit-tests.yml, test/gen_integration.sh
bump our node12 actions to the new v3 node 16 versions as they are deprecated soon
https://github.com/Azure/draft/actions/runs/4195969311
we get a ton of warning at the moment due to this
=> bump node12 actions

template/dockerfiles/clojure/Dockerfile, template/dockerfiles/clojure/draft.yaml, template/dockerfiles/gradle/Dockerfile, template/dockerfiles/gradle/draft.yaml, template/dockerfiles/java/Dockerfile, template/dockerfiles/java/draft.yaml, test/integration/gradle/helm.yaml, test/integration/gradle/kustomize.yaml, test/integration/gradle/manifest.yaml, test/integration/java/helm.yaml, test/integration/java/kustomize.yaml, test/integration/java/manifest.yaml, test/integration_config.json
Openjdk image has been deprecated and we need to swap to a new image that has JRE support for version > 11.
=> Updating Java images from OpenJDK to Eclipse Temurin

.github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, template/dockerfiles/go/Dockerfile, test/integration/go/helm.yaml, test/integration/go/kustomize.yaml, test/integration/go/manifest.yaml, test/integration_config.json
add the non-module supporting `go` dockerfile support to an integration test
=> add go dockerfile test and no modules

.github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, cmd/generate-workflow.go, pkg/workflows/workflowconfig.go, pkg/workflows/workflows_test.go, template/workflows/helm/.github/workflows/azure-kubernetes-service-helm.yml, template/workflows/helm/draft.yaml, template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, template/workflows/kustomize/draft.yaml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml, template/workflows/manifests/draft.yaml, test/gen_integration.sh
Adds a flag that allows the user to specify the path to the docker build context (_build-context-path_).
This PR is a clean version of this PR with all commits signed: https://github.com/Azure/draft/pull/201
=> Feature/build-context-path for generate-workflows

test/integration/gradle/helm.yaml, test/integration/gradle/kustomize.yaml, test/integration/gradle/manifest.yaml, test/integration_config.json
Specify gradle version in the image tag with jdk
A previous image change updated the default tag to use the image `gradle` with tag `jdk11`, which doesn't specify a gradle version. Our demo repo uses gradle 7, so we need to specify this in the docker image tag by changing it to `7-jdk11`.
Long-term it could be beneficial to add better parsing to draft that allows us to detect which version of gradle a repo is using, since using the wrong version of gradle will prevent the image from building
The image tag can take a both values in the format  `<GRADLE VERSION>-jdk<JDK-VERSION>`
Existing integration tests now pass with the updated image
=> gradle specific version in dockerfile

.github/workflows/integration-install.yml, scripts/install.sh
Integration tests for multiple OS - including windows, macos and fixes https://github.com/Azure/draft/issues/211
=> Integration test for multiple OS

template/dockerfiles/rust/draft.yaml, test/integration/rust/helm.yaml, test/integration/rust/kustomize.yaml, test/integration/rust/manifest.yaml
The current default rust version is no longer compatible with the required packages, causing cargo to fail. This bumps it to a compatible version
=> bump rust version to fix e2e

cmd/create.go, pkg/filematches/filematches.go, pkg/languages/defaults/python.go, pkg/languages/defaults/python_test.go, pkg/languages/languages.go, pkg/reporeader/readers/localfsreader.go, pkg/reporeader/reporeader.go
add a new interface and pattern for extracting defaults from a repo in draft.
the current pattern only supports using pre- set defaults, which can then be replaced by a user-provided value.
Similar to the way the `TemplateWriter` interface was used to abstract the filesystem writing operations, this PR introduces the `RepoReader` interface that abstracts reading data from a repo's files.
The main goal of this is to allow more intelligent defaults such as detecting a compatible image version or entrypoint script by reading the files in a repo during `draft create` execution.
By allowing prompt defaults to be set through extracting information from the repo files, we can greatly improve the probability that a default value is correct.
An example of this is the great work on #214  that could …
=> add reporeader interface and an example extractor for python

README.md
update our readme with the list of supported flags for wrapping the draft binary
=> update readme for supported flags

.github/workflows/integration-install.yml, scripts/install.sh
This PR is to fix the issue where GH action for install script fails intermittent, introducing retry will retry getting the tag name from releases.  
Root cause: due to github rate limiting for unauthenticated requests , it is failing with below error. Fixing this with authenticated requests using github token from env variable. 
=> retry releases to get tag name

cmd/create.go, pkg/languages/defaults/gradle.go, pkg/languages/defaults/gradle_test.go, pkg/languages/defaults/testdata/sample.gradle, pkg/languages/languages.go, template/dockerfiles/gradlew/.dockerignore, template/dockerfiles/gradlew/Dockerfile, template/dockerfiles/gradlew/draft.yaml
This PR is to include gradle wrapper to draft flow and detect the defaults from build.gradle for java projects. 
=> changes to support gradle wrapper and defaults

.github/workflows/integration-linux.yml, cmd/create.go, cmd/create_test.go, pkg/languages/defaults/python.go, pkg/languages/defaults/python_test.go, pkg/languages/languages.go, pkg/reporeader/reporeader.go, template/dockerfiles/python/Dockerfile, template/dockerfiles/python/draft.yaml, test/gen_integration.sh
Added code to extract the python entry point file and set it in the generated Dockerfile.
=> changes for python file entry point detection

template/deployments/helm/charts/production.yaml, template/deployments/helm/charts/values.yaml, template/deployments/kustomize/base/deployment.yaml, template/deployments/manifests/manifests/deployment.yaml, template/dockerfiles/python/Dockerfile, test/templates/helm/charts/production.yaml, test/templates/helm/charts/values.yaml, test/templates/helm_prod_values.yaml
Change image pull policy to always, following best practices 
=> image pull policy always

template/dockerfiles/gradle/draft.yaml, template/dockerfiles/gradlew/draft.yaml, template/dockerfiles/java/draft.yaml
Use more current jdk/jre image for default java dockerfiles
=> Bump default jdk/jre

pkg/providers/azure.go, pkg/providers/providersutils.go
When there are multiple subscriptions under the local azure account, the `setup-gh` command would fail to discover the correct resource group with error like this:
```
Error: resource group not found
```
This is because the resource group validation logic is expecting 1) the local `azcli` has fetched all subscriptions 2) the resource group is created under the active subscription. However these assumptions are incorrect when running with command like this:
```
$ draft setup-gh -s <my-sub-id> -g <my-rg-name>
```
To get the resource group correctly, this pull request added `--subscription` parameter on the query command. I also enhanced the error message a bit to provide more details on missing resource group error.
Please delete options that are not …
=> fix: query resource group under giving subscription id

.github/workflows/e2e-info.yml, .github/workflows/integration-install.yml, .github/workflows/integration-json.yml, .github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, .github/workflows/poll-starter.yml, .github/workflows/release-and-publish.yml
These changes are made in correlation with the following changes coming soon in the GH actions permissions. Please take a kind look. ❤️🙏☕️
* https://docs.opensource.microsoft.com/github/apps/permission-changes/
To start with going with the most safest option with read only permission, for `publish` we need the `write for content`. Given this will spread pretty soon lets try this out and I will gradually open similarity changes in other repos I know.
For, release only workflow **Sample test** if we do `content: read` for publish we will get some error like this which I tested in my fork for other project.
Thank you. ❤️🙏
=> Changes in correlation with new GH Action Permission Changes.

README.md
update badges on readme to follow main branch, as they currently track most recent PR, which isn't useful for consuming releases on main page
=> update badges on readme to follow main branch

.github/workflows/e2e-info.yml, .github/workflows/integration-install.yml, .github/workflows/integration-json.yml, .github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, .github/workflows/release-and-publish.yml, .github/workflows/unit-tests.yml, Dockerfile, go.mod, scripts/install.sh, template/dockerfiles/go/Dockerfile, template/dockerfiles/gomodule/Dockerfile, test/gen_integration.sh, test/integration/go/helm.yaml, test/integration/go/kustomize.yaml, test/integration/go/manifest.yaml, test/integration/gomodule/helm.yaml, test/integration/gomodule/kustomize.yaml, test/integration/gomodule/manifest.yaml, test/integration/rust/helm.yaml, test/integration/rust/kustomize.yaml, test/integration/rust/manifest.yaml, test/integration_config.json
Update draft to go 1.22
Update go non-module dockerfile template as the entrypoint file is needed it is hard-coded to `main.go`- this can be updated later to use the ENTRYPOINT variable
=> update draft to go 1.22

template/dockerfiles/gomodule/Dockerfile
update the gomodule dockerfile template to use a multistage build to reduce image size and improve security
=> gomodule multistage build

CHANGELOG.md
- [#277](https://github.com/Azure/draft/pull/277) Updates/Fixes for draft. Addes generator label to manifests
- [#275](https://github.com/Azure/draft/pull/275) Add NOTICE file
- [#274](https://github.com/Azure/draft/pull/274) gomodule multistage build
- [#273](https://github.com/Azure/draft/pull/273) finighing safeguard additions
- [#272](https://github.com/Azure/draft/pull/272) sdk calls for assignsprole
- [#271](https://github.com/Azure/draft/pull/271) update draft to go 1.22
- [#269](https://github.com/Azure/draft/pull/269) yaml file extension validation
- [#262](https://github.com/Azure/draft/pull/262) sdk calls for getTenantID
- [#242](https://github.com/Azure/draft/pull/242) changes in correlation with new GH action permission changes …
=> Release v34

pkg/prompts/prompts.go, pkg/prompts/prompts_test.go
Prompt the user to enter the application name.
Sanitize the user input.
If the user does not provide any input, uses the current directory name as the default.
Sanitize the directory name and ensure it meets the K8s label standards.
If neither the user input nor the directory name meets the standards, default to "my-app".
If the user input is empty it defaults to the directory name
validator for app name
=> adding logic for generating default app name

pkg/safeguards/preprocessing/preprocessing.go, pkg/safeguards/preprocessing/preprocessing_helpers.go, pkg/safeguards/preprocessing/preprocessing_test.go, pkg/safeguards/preprocessing/preprocessing_test_helpers.go, pkg/safeguards/tests/testmanifests/nochart-invalid/templates/deployment.yaml, pkg/safeguards/tests/testmanifests/nochart-invalid/values.yaml
- Adding IsHelm() helper function which returns true a directory/file contains a Chart.yaml file. Does not validate the Chart.yaml itself, just checks to see it exists. 
- Moved IsKustomize() to preprocessing_helpers.go as well to reduce clutter in preprocessing/ preprocessing_test.go.
- Added a test folder which for a test case which should return false for a dir without Chart.yaml
Added Unit tests
=> Adding IsHelm helper function

template/workflows/helm/.github/workflows/azure-kubernetes-service-helm.yml, template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml
This PR adds the resource group and cluster name fields to the k8s/deploy action within the workflow templates. These are necessary as k8s/deploy requires them to run az aks command invoke for kubectl commands within the private cluster.
=> Added k8s/deploy Inputs for Private Cluster Support

cmd/validate.go, cmd/validate_test.go, cmd/validate_test_helpers.go, pkg/safeguards/helpers.go, pkg/safeguards/helpers_test.go, pkg/safeguards/manifestresults.go, pkg/safeguards/preprocessing/preprocessing.go, pkg/safeguards/preprocessing/preprocessing_helpers.go, pkg/safeguards/preprocessing/preprocessing_test.go, pkg/safeguards/preprocessing/preprocessing_test_helpers.go, pkg/safeguards/tests/testmanifests/expected-resources.yaml, pkg/safeguards/types/constants.go, pkg/safeguards/types/types.go
Replacing ManifestFile Path property with yaml content as []byte. There is no need to write rendered manifests to a temporary directory now. Manifests are rendered and written in memory for validation to handle later.
Unit tests were updated to ensure validation is not dependent on writing rendered files to a temp dir. All files are written/returned in memory
=> Removing Manifest Path property, replacing with []byte content

pkg/workflows/workflows.go, template/deployments/helm/charts/templates/namespace.yaml, template/workflows/helm/.github/workflows/azure-kubernetes-service-helm.yml, template/workflows/helm/draft.yaml, template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml
1. Updated information on environment variables in comments
2. Removed bake step for helm deployments
=> Update workflow templates

CHANGELOG.md, template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml
=> Fix for private cluster support for kube and kustomize deployment

pkg/azurePipelines/azurePipelines.go, pkg/azurePipelines/azurePipelines_test.go, pkg/fixtures/pipelines/kustomize.yaml, pkg/fixtures/pipelines/manifests.yaml, pkg/fixtures/validatetemplate.go, template/azurePipelines/kustomize/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/manifests/.pipelines/azure-kubernetes-service.yaml
=> Migrating the Azpipeline templates to Go templates

template/dockerfiles/go/Dockerfile, template/dockerfiles/go/draft.yaml, template/dockerfiles/gomodule/Dockerfile, template/dockerfiles/gomodule/draft.yaml
Adds updated golang versions, and moves env setting to the proper section
=> update go versions and dockerfile template

.github/pull_request_template.md
Updating PR template to include Refactor option, updating descriptions in some sections.
=> Adding Refactor option, removing some description from PR template

CHANGELOG.md
Release 0.0.39
- [#406](https://github.com/Azure/draft/pull/406) Migrating Addons to generic handler
- [#403](https://github.com/Azure/draft/pull/403), [#404](https://github.com/Azure/draft/pull/404) Adding PDB template
- [#400](https://github.com/Azure/draft/pull/400) Migrating azurePipelines to Generic handler
- [#399](https://github.com/Azure/draft/pull/399) Migrating Dockerfile templates to Generic handler
- [#398](https://github.com/Azure/draft/pull/398) Creating HPA template
- [#395](https://github.com/Azure/draft/pull/395) Upgrade from deprecated kubeval to kubeconform
- [#393](https://github.com/Azure/draft/pull/393) Migrate Deployments templates to generic handler
- [#391](https://github.com/Azure/draft/pull/391) Creation of generic template handler
- …
=> Changelog Release 0.0.39

.github/workflows/integration-json.yml, .github/workflows/integration-linux.yml, .github/workflows/integration-windows.yml, .github/workflows/poll-starter.yml, test/gen_integration.sh
Following PR will take care of this Breaking change for upload-artifact https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/#artifacts-v3-brownouts
For folks who want to know more about why pinning to specific comment please read here: https://www.stepsecurity.io/blog/pinning-github-actions-for-enhanced-security-a-complete-guide 
Hence moved to latest v4 release and pinned it to the commit.
* https://github.com/actions/download-artifact/releases/tag/v4.1.8 
* https://github.com/actions/upload-artifact/releases/tag/v4.4.3
Thanks heaps.
=> Preemptive fix for the GH upcoming breaking changes.

.github/dependabot.yml
the grouped dependabot PRs are leading to failed integration tests with several manual interventions on the PRs, so i proposed reverting to individual PRs to allow merging the version bumps that work
=> no dependabot groups they didnt work 

CHANGELOG.md, package-lock.json
Release v0.17.1 update to include fleet bump and k8s-deploy v5 with privatecluster tmp dir fix https://github.com/Azure/k8s-deploy/pull/327
=> release v0.17.1

.github/workflows/integration-per-language.yml, pkg/config/draftconfig_template_test.go, template/workflows/helm/draft.yaml, template/workflows/kustomize/draft.yaml, template/workflows/manifests/draft.yaml
enforce default clusterresourcetype in draft.yaml instead of tests
don't prompt for this variable, instead allow override, but default to AKS managed clusters
=> cluster resource type default enforcement

CHANGELOG.md
release v0.17.2 contains the following changes
- [476](https://github.com/Azure/draft/pull/476) Added default value for CLUSTERRESOURCETYPE in draft.yaml
- [477](https://github.com/Azure/draft/pull/477) Explicitly require jobs for each language to allow failure to be reported and prevent PR merging in case of a failure
- [479](https://github.com/Azure/draft/pull/479) Remove helm `wait` flag for fleet clusters
=> release v0.17.2

pkg/fixtures/deployments/helm/charts/values.yaml, pkg/fixtures/deployments/kustomize/base/deployment.yaml, pkg/fixtures/deployments/manifest/manifests/deployment.yaml, template/deployments/helm/draft.yaml, template/deployments/kustomize/draft.yaml, template/deployments/manifests/draft.yaml, test/integration/clojure/helm.yaml, test/integration/clojure/kustomize.yaml, test/integration/clojure/manifest.yaml, test/integration/gradle/helm.yaml, test/integration/gradle/kustomize.yaml, test/integration/gradle/manifest.yaml, test/integration/java/helm.yaml, test/integration/java/kustomize.yaml, test/integration/java/manifest.yaml
use the default k8s probe values instead of overriding them on tests https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
=> use default k8s probe settings

.github/dependabot.yml
Enable depdneabot for following
1. **Checks for Updates:**  
- Dependabot scans **GitHub Actions workflows** (e.g., `.github/workflows/*.yml`).
- Identifies actions that need updating (e.g., `actions/setup-go@v5` → latest SHA).
2. **Creates PRs for Updates:**  
- It **replaces outdated versions** with the latest **commit SHA**.
- Adds a **"dependencies" label** to PRs for easy identification.
4. **Runs on a Weekly Schedule:**  
- Dependabot checks for new versions **once a week**.
Thanks heaps and FYI: @davidgamero ❤️ lets merge this https://github.com/Azure/draft/pull/487 and then we can get this in for all resolving from next week onwards, thanks heaps
=> Scan workflows for unpinned GitHub Actions.

pkg/fixtures/workflows/github/helm/.github/workflows/azure-kubernetes-service-helm.yml, pkg/fixtures/workflows/github/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, pkg/fixtures/workflows/github/manifests/.github/workflows/azure-kubernetes-service.yml, template/workflows/helm/.github/workflows/azure-kubernetes-service-helm.yml, template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml
=> Add private cluster support for namespace creation/validation

pkg/fixtures/deployments/helm/charts/values.yaml, pkg/fixtures/deployments/kustomize/base/deployment.yaml, pkg/fixtures/deployments/manifest/manifests/deployment.yaml, template/deployments/helm/draft.yaml, template/deployments/kustomize/draft.yaml, template/deployments/manifests/draft.yaml
reduce our base resource requests to 0.5 cpu and 0.5Gi to better fit our target workload sizes and avoid requesting unnecessary resources
=> reduce base resource requests to 0.5Gi and 0.5 cpu

README.md
Update REAME to use the homebrew core tap that [includes draft](https://github.com/Homebrew/homebrew-core/pull/198839)
Reorganize readme to prioritize installation steps
=> update to reflect homebrew core tap

pkg/fixtures/workflows/azurepipelines/kustomize/.pipelines/azure-kubernetes-service.yaml, pkg/fixtures/workflows/azurepipelines/manifests/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/kustomize/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/kustomize/draft.yaml, template/azurePipelines/manifests/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/manifests/draft.yaml
Add docker build context support for ADO pipelines
=> Add build context support for ADO pipelines

CHANGELOG.md, cmd/create.go, cmd/create_test.go, cmd/root.go, cmd/setupgh.go, cmd/setupgh_test.go, pkg/linguist/linguist.go
In order to better serve automated and batch workflows, as well as the wrapped-binary consumption patter, i propose adding a new `interactive` flag that will error on stderr instead of interactively prompting.
this will open up automation options like running in github actions with better error handing
=> add `interactive` flag 

CHANGELOG.md
release the new tomcat template and dependabot fixes
=> release 0.17.7

pkg/fixtures/manifests/ingress/ingress.yaml, template/manifests/Ingress/manifests/ingress.yaml
update ingress name variable to use the correct variable from draft.yaml https://github.com/Azure/draft/blob/fdbedf7c7ecbb3a72eba0567ac6aac0b4ffadd66/template/manifests/Ingress/manifests/draft.yaml#L7
=> fix ingress name variable

pkg/fixtures/workflows/github/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, pkg/fixtures/workflows/github/manifests/.github/workflows/azure-kubernetes-service.yml, template/workflows/kustomize/.github/workflows/azure-kubernetes-service-kustomize.yml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml
For a Fleet workflow, the user doesn't necessarily have permissions to annotate the namespace. By default, we will turn this off for fleet resources in the workflow to fix this warning: 
=> Removing annotate-namespace for fleet resources

pkg/fixtures/workflows/azurepipelines/kustomize/.pipelines/azure-kubernetes-service.yaml, pkg/fixtures/workflows/azurepipelines/manifests/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/kustomize/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/kustomize/draft.yaml, template/azurePipelines/manifests/.pipelines/azure-kubernetes-service.yaml, template/azurePipelines/manifests/draft.yaml
The azure pipeline templates did not have dockerfile path as an env variable and used the default file path. Added a new parameter `DOCKERFILE` in `draft.yaml` so that custom Dockerfile path can also be passed.
=> Add dockerfile param to az pipeline

cmd/create.go, cmd/root.go
fix https://github.com/Azure/draft/issues/561
the interactive flag introduced a bug defaulting to skipping port inputs on the `draft create` command
=> default interactive true

pkg/fixtures/workflows/github/manifests/.github/workflows/azure-kubernetes-service.yml, template/dockerfiles/rust/draft.yaml, template/workflows/manifests/.github/workflows/azure-kubernetes-service.yml, test/integration/rust/helm.yaml, test/integration/rust/kustomize.yaml, test/integration/rust/manifest.yaml
Adding azlogin step to fix Docker login error in fleet deployment annotate resources step
=> Adding azlogin step
